### ISSUE TITLE
Spec Enhancement Request: Specify how different noise functions correlate.

### ISSUE THREAD

**Issue by loren-osborn** [imageworks/OpenShadingLanguage#1024]
Please specify how different `noise()` `noisetype`s correspond to each other: (This may only relate to the reference implementation, but it would be nice if future implementations were consistent with the reference implementation here.)

I liked how the spec spelled out that `cellnoise(...)` was equivalent to `noise("cell", ...)`, and how it also said that `cellnoise(x)` and `cellnoise(floor(x))` were also equivalent. In cases where someone wants to maintain backward compatibility with previous shader versions, it might be helpful to know, for instance that `noise("cell", x)` returns the same result as `noise("hash", floor(x))`. (I have no expectation that this is the case. It's simply an example.)

As existing implementations may already disagree with the reference implementation on these, the spec should make this correlation optional.

### Problem

It is difficult to increase the entropy resolution of code using `cellnoise(...)` or `noise("cell", ...)` without special-casing integer values unless you know how to emulate the `"cell"` behavior with another type like `"hash"`. If the spec spelled out a correlation, this would be much easier.

**Expected behavior:**  The spec might say something like:
*  `noise("cell", x)` returns the same result as `noise("hash", floor(x))`

**Actual behavior:**  No correlation is specified.

### Steps to Reproduce

1. Release software with shaders using `cellnoise()` that you wish to preserve behavior of.
2. Enhance shader to want values **between** cell boundries in newly supported cases.
3. Either you:
    * Scale `cellshader()` input to allow cell boundries at a different frequency. (This shifts all your integer pseudo-random values.
    * Special-case integer boundaries to use `cellnoise()`. This increases code complexity.
    * Find a way to generate `cellnoise()` from `hashnoise()` by experimentation or reverse-engineering the code.

### Versions

* OSL branch/version: 1.10
* OS: Mac, Windows and Linus
* C++ compiler: n/a
* LLVM version: n/a
* OIIO version: n/a

**Comment by lgritz** [comment]
It may be that the current implementation of noise("hash") is identical to noise("cell") at exact integer values, but this property is not explicitly part of the design and I don't think I would have wanted to enshrine that guarantee into the language spec. 

In general, there are no guarantees that I'm aware of between the different noise functions. For example, sometimes new users think that maybe there is a relationship between noise on 1D, 2D, and 3D domain -- i.e. that noise(float f) should be the same as noise(f, 0) or noise(point(f,0,0)). But in fact, neither of those are true (and wouldn't be desirable, for complicated reasons related to the range and power spectrum of noise).

**Comment by loren-osborn** [comment]
> It may be that the current implementation of noise("hash") is identical to noise("cell") at exact integer values, but this property is not explicitly part of the design and I don't think I would have wanted to enshrine that guarantee into the language spec.
It would be helpful to my current project to know if this currently happens to be true. Do you know one way or the other?

I realize there are reasons to avoid adding this specificity to the spec:
* This would tie other implementors to what was intended to be a reference implementation detail.
* Some APIs or hardware implementations may have accelerated implementations of these that contradict these correlations. We don’t want to prevent an implementor from using these in violation of the spec.
* Some implementors may devise new and better ways of generating these noise function outputs that may violate these correlations. Again we don’t want to discourage this innovation by mandating these correlations.
* This may push the spec closer to an undesirable “pixel perfect” definition, preventing differences in implementations

That said, I was providing a use case where **suggesting** a correlation between “hash” noise (as a lowest common denominator) and other noise functions **may** be beneficial for the sake of backward compatibility. This is just a suggestion, and may not be a good idea, but I thought it worth suggesting.

I was suggesting language similar to:
> `noise(“foo”, ...)`  function MAY be implemented as `foo_transform(noise(“hash”, ...))` but this relationship is not guaranteed.

**Comment by lgritz** [comment]
OK, that's fair. Let me see if I can clarify it.

**Comment by lgritz** [comment]
I'm going to close this as an ongoing issue. I'll think about whether and how to mention this in the spec.

**Comment by loren-osborn** [comment]
@lgritz, I really neither want to open a new issue, nor reopen this one but wanted to mention this for your feedback:

I’m trying to move more precomputation and loop unrolling to compile time. It would be nice if the language provided more mechanisms for this, but i’m considering using https://github.com/pfultz2/Cloak to leverage the preprocessor for this. It’s a scaled-down version of Chaos-PP, that later became Boost Preprocessor... I think Boost Preprocessor is much too big for runtime compilation use, but cloak weighs in at a single 3kb file.

All three of these sit on top of the preprocessor and should be pretty-language agnostic...what are your thoughts about adding more support in the language for compile time precomputation and optimization using techniques like this.

This is really just a request for some thought and feedback. Thank you in advance.

**Comment by lgritz** [comment]
Can you explain what would that do that's useful? I can't understand from the project you link to what it does.

**Comment by loren-osborn** [comment]
@lgritz, the specific case that i’m currently interested in is explicit loop unrolling... and a non-trivial loop at that. The code i’m looking at had a 5 case of-else chain each with a successively shorter list of assignments in it. I rewrote this as a loop for clarity, but was encouraged *NOT* to submit it when another developer optimized some of the assignments with swizzling. I am sure the code with the swizzling is more performant, but I would prefer to have a way to express that in a more readable loop-like way, and expand to the original code at compile time... including the bundling of multiple assignments into swizzling. 

The specific code i’m talking about is from here:
https://developer.blender.org/diffusion/B/browse/master/intern/cycles/kernel/shaders/node_voronoi_texture.osl;04c54dec44568a4903b5f8e29cad4b3e466fb6e0?as=source
but i’ll Include changes from memory I mentioned above:
```
if (d < da[0]) {
   da[3] = da[2];
    da[2] = da[1];
    da[1] = da[0];
    da[0] = d;
 
    pa.yzw = pa.xyz;
    pa[0] = vp;
}
else if (d < da[1]) {
    da[3] = da[2];
    da[2] = da[1];
    da[1] = d;
 
    pa.zw = pa.yz;
    pa[1] = vp;
}
else if (d < da[2]) {
    da[3] = da[2];
    da[2] = d;
 
    pa.w = pa.z;
    pa[2] = vp;
}
else if (d < da[3]) {
    da[3] = d;
    pa[3] = vp;
}


```

**Comment by lgritz** [comment]
I'm still not quite sure I understand specifically what you are asking me to do on my end.
