### ISSUE TITLE
Failed assertion: Init ops are not currently supported in OptiX

### ISSUE THREAD

**Issue by DeclanRussell** [imageworks/OpenShadingLanguage#1040]
### Problem

Init opts are currently not supported in the OptiX run time. This means that using such notation as initializing vector parameters from global variables (e.g. `vector v = vector(u, v, 0)` ) is not supported and you will hit the assert in the tittle of this ticket. This notation is used quite frequently in the publicly available OSL shaders that the 3DSMax guys have written [here](https://github.com/ADN-DevTech/3dsMax-OSL-Shaders) and its a shame not to be able to use them. Is there any plans on adding support for these anytime soon? At least having a graceful fallback so that the run time doesn't crash with these shaders would be great!

### Steps to Reproduce
The following patch will modify the testoptix test to reproduce the issue. Simply run,
`testrender.exe -optix scene.xml -r 320 320 out.exr`
This will give the following assert,
`llvm_instance.cpp:495: failed assertion '! sym.has_init_ops() && "Init ops are not currently supported in OptiX"'`
```diff
--- a/testsuite/testoptix/checkerboard.osl
+++ b/testsuite/testoptix/checkerboard.osl
@@ -41,7 +41,7 @@ checkerboard
         [[  string description = "scale factor for s coordinate" ]],
     float scale_t = 4
         [[  string description = "scale factor for t coordinate" ]],
-    color Ca = color(1, 1, 1)
+    color Ca = color(u, v, 1)
         [[  string description = "color of even squares" ]],
     color Cb = color(0, 0, 0)
         [[  string description = "color of odd squares" ]],
diff --git a/testsuite/testoptix/scene.xml b/testsuite/testoptix/scene.xml
index 1a2956e..e33f646 100644
--- a/testsuite/testoptix/scene.xml
+++ b/testsuite/testoptix/scene.xml
@@ -4,7 +4,6 @@
    <ShaderGroup>
       param float scale_s 20;
       param float scale_t 20;
-      param color Ca 0.1 0.1 0.1;
       param color Cb 0.5 0.5 0.5;
       shader checkerboard tex;
       shader matte layer1;

```

### Versions

* OSL branch/version: master
* OS: Windows 10 / Centos 6.0
* C++ compiler: clang 5
* LLVM version: 5.0.2
* OIIO version: master

**Comment by lgritz** [comment]
Fixed by #1057
