### ISSUE TITLE
Trouble running serialize-bc.py

### ISSUE THREAD

**Issue by sambler** [imageworks/OpenShadingLanguage#1068]
### Problem

**Expected behavior:**  generation of llvm_ops.bc.cpp

**Actual behavior:**  

```
src/liboslexec/serialize-bc.py", line 14, in <module>
    f_out.write('0x%s,\n' % c.encode('hex'))
AttributeError: 'int' object has no attribute 'encode'

```

The encode I see is [`str.encode()`](https://docs.python.org/3/library/stdtypes.html#str.encode) which is to convert the string storage encoding - eg to 'utf-8'.

The `c` in `for c in f_in.read():` is an integer, as `f_in` is a binary file being opened with `'rb'`.

I expect the use of [`hex()`](https://docs.python.org/3/library/functions.html#hex) would give the intended result.

    f_out.write('%s,\n' % hex(c))

---

Also the use of `'%s' % val` is old style, using py3 [`str.format()`](https://docs.python.org/3/library/stdtypes.html#str.format) should be considered, with [f-strings in 3.6+](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals) also a valid option.

    f_out.write('{},\n'.format(hex(c)))

or - 3.6+

    f_out.write(f'{hex(c)},\n')

### Versions

* OSL branch/version: master - 30f64c07c28f
* OS: FreeBSD 12
* C++ compiler: clang 8/9
* LLVM version: 8/9
* OIIO version: 2.0.11

**Comment by lgritz** [comment]
Can you try #1071 and see if that works for you?

**Comment by sambler** [comment]
IS there a reason this was left open after the merge?

**Comment by lgritz** [comment]
No, I think maybe I didn't mention the right incantation on the other ticket to cause this one to automatically close when it was merged.
