### ISSUE TITLE
OSL 1.10.x series fails to build with llvm 10.x

### ISSUE THREAD

**Issue by david-geiger** [imageworks/OpenShadingLanguage#1134]
Hi,

I tried on Mageia Cauldron to build OSL 1.10.9 with llvm 10.0.0 but it fails to build:

> /usr/include/llvm/ADT/PointerIntPair.h:150:8: error: enumerator value for 'IntShift' is not an integer constant
  150 |   enum : uintptr_t {
      |        ^
make[2]: *** [src/liboslexec/CMakeFiles/oslexec.dir/build.make:164: src/liboslexec/CMakeFiles/oslexec.dir/shadingsys.cpp.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/OpenShadingLanguage-Release-1.10.9/build'
make[1]: *** [CMakeFiles/Makefile2:1326: src/liboslexec/CMakeFiles/oslexec.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

### Versions

* OSL branch/version: 1.10.9
* OS: Mageia Linux
* C++ compiler: 9.3.0
* LLVM version: 10.0.0
* OIIO version: 2.0.13

Regards,
David

**Comment by lgritz** [comment]
We haven't fixed any 1.10.x releases to work with LLVM 10 yet. (Though the current OSL master has those fixes.)

**Comment by lgritz** [comment]
As an aside, and possibly even more relevant to your specific error -- LLVM 10.0 does not work with C++11. It requires a minimum of C++14. So if you want to build against LLVM 10.0, it is required that you build OSL with C++14.

**Comment by david-geiger** [comment]
So ok compiling with C++14 fixes build.

**Comment by lgritz** [comment]
Great. Closing.

**Comment by lgritz** [comment]
I will add a check that will give a more helpful build time error if you are using a combination of C++11 and LLVM 10.
