### ISSUE TITLE
OpenImageIO not found

### ISSUE THREAD

**Issue by vikasTmz** [imageworks/OpenShadingLanguage#1163]
### Problem

Unable to build OSL. Get the following error:

```
Try setting OpenImageIO_ROOT ? 
CMake Error at src/cmake/externalpackages.cmake:142 (message):
  OpenImageIO is required, aborting.

```
[[Output of make VERBOSE=1]](https://gist.githubusercontent.com/vikasTmz/98b072d037ebf84b04ff19e5e0cd5f13/raw/cd966f6ef96e80f08e97870b299241678b905d1d/osl_make_verbose)

### Versions

* OIIO version: 2.2.3

I built OIIO locally and I followed the instructions in INSTALL.md:
```
After building OpenImageIO, if you don't have it installed in a "standard" place (like /usr/include), 
you should set the environment variable $OPENIMAGEIOHOME to point to the compiled 
distribution, as well as for $OPENIMAGEIOHOME/lib to be in your LD_LIBRARY_PATH (or 
DYLD_LIBRARY_PATH on OS X) and then OSL's build scripts will be able to find it.
```
and also set `OpenImageIO_ROOT`.

**Comment by lgritz** [comment]
If the "Try setting OpenImageIO_ROOT" message was printed (as it was in your make output), that means that it wasn't set at all. If OIIO is not found but OpenImageIO_ROOT is set, it will print the value.

**Comment by lgritz** [comment]
Did you close the ticket because you found a solution? Or are you still having trouble?

**Comment by vikasTmz** [comment]
Sorry for the delay, I found a solution; had a silly typo which went unnoticed.
