### ISSUE TITLE
Which version of optix is supported?

### ISSUE THREAD

**Issue by jiapei100** [imageworks/OpenShadingLanguage#1170]
### Problem

Just have **NO** idea which version of optix is current **OSL**supporting? I'm trying the **MOST recent **NVIDIA-OptiX-SDK-7.0.0-linux64**, but I can see the following 3 libraries **ONLY** .

```console
> find . -depth -name "*.so"
./SDK/build_18.04/lib/libglfw.so
./SDK/build_18.04/lib/libsutil_7_sdk.so
./SDK/build_18.04/lib/libglad.so
```

### Versions

* OSL branch/version: master branch, May 9, 2020.
* OS: Ubuntu 18.04.4
* C++ compiler: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
* LLVM version: llvm-9-runtime/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
* OIIO version: 2.1.14

Anyway, I'm building **OSL** without **optix** for now, but prefer to have **optix** enabled...

### Finally

Without enabling **optix**, I still obtained the following **ERROR** messages:

```console
Error running '-header-filter=(OSL)|(OSL)|(osl)|(_pvt.h)': No such file or directory
src/liboslexec/CMakeFiles/oslexec.dir/build.make:202: recipe for target 'src/liboslexec/CMakeFiles/oslexec.dir/dictionary.cpp.o' failed
make[2]: *** [src/liboslexec/CMakeFiles/oslexec.dir/dictionary.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Error running '-header-filter=(OSL)|(OSL)|(osl)|(_pvt.h)': No such file or directory
Error running '-header-filter=(OSL)|(OSL)|(osl)|(_pvt.h)': No such file or directory
src/liboslexec/CMakeFiles/oslexec.dir/build.make:189: recipe for target 'src/liboslexec/CMakeFiles/oslexec.dir/closure.cpp.o' failed
make[2]: *** [src/liboslexec/CMakeFiles/oslexec.dir/closure.cpp.o] Error 1
src/liboslexec/CMakeFiles/oslexec.dir/build.make:176: recipe for target 'src/liboslexec/CMakeFiles/oslexec.dir/shadingsys.cpp.o' failed
make[2]: *** [src/liboslexec/CMakeFiles/oslexec.dir/shadingsys.cpp.o] Error 1
Error running '-header-filter=(OSL)|(OSL)|(osl)|(_pvt.h)': No such file or directory
src/liboslexec/CMakeFiles/oslexec.dir/build.make:215: recipe for target 'src/liboslexec/CMakeFiles/oslexec.dir/context.cpp.o' failed
make[2]: *** [src/liboslexec/CMakeFiles/oslexec.dir/context.cpp.o] Error 1
make[2]: Leaving directory '....../OpenShadingLanguage/build_18.04'
CMakeFiles/Makefile2:1303: recipe for target 'src/liboslexec/CMakeFiles/oslexec.dir/all' failed
make[1]: *** [src/liboslexec/CMakeFiles/oslexec.dir/all] Error 2
make[1]: Leaving directory '....../OpenShadingLanguage/build_18.04'
Makefile:185: recipe for target 'all' failed
make: *** [all] Error 2
```

Any suggestions?
Pei

**Comment by lgritz** [comment]
It should build against OptiX 6 or 7.

I'm not sure what's up with your OptiX installation, I think you should certainly have more than that, but I can't really tell what directory you're looking at or where things are expected to be installed on your system.

As for the error messages without Optix, that doesn't make sense at all. How are you launching the cmake and build? That bit about '-header-filter' should only be if you are running the static analysis by enabling CLANG_TIDY. Don't do that!

**Comment by jiapei100** [comment]
@lgritz 

Without **enable optix**, **OSL** can be successfully built. I'm using the **MOST up-to-date** OptiX™ SDK 7.0 .

BTW, what is **optixu** ?

**Comment by fpsunflower** [comment]
Optix 7 support has not been merged into master yet. See #1111 for the current status (we hope to finish this soon).

Also keep in mind that Optix support is highly experimental and is only relevant if you are planning on working on integrating OSL and Optix into your own renderer. 

Where are you seeing `optixu` ?

**Comment by fpsunflower** [comment]
I looked at the cmake setup,`optixu` is a library part of the Optix 6 distribution. It doesn't exist in Optix 7 which is a very different API.

**Comment by jiapei100** [comment]
@fpsunflower 

Hi, Thank you for you detailed explaination, and good to know the details... I actually just need to build blender, which seems to have used OSL ???

**Comment by jiapei100** [comment]
@lgritz 
Hi, Larry.. You are absolutely correct.... **Do NOT enable clang-tidy** .
