### ISSUE TITLE
Can't build. The version of OpenImageIO is 2.1.12.0-1, build system is mingw64. 

### ISSUE THREAD

**Issue by CyangYu** [imageworks/OpenShadingLanguage#1187]
OpenShadingLanguage\src\liboslexec\shadingsys.cpp:3267:5: error: no matching function for call to 'open'
    OIIO::Filesystem::open(groupfile, groupfilename);
    ^~~~~~~~~~~~~~~~~~~~~~
D:\Develop\Library\msys2\mingw64\include\OpenImageIO/filesystem.h:204:15: note: candidate function not viable: no known conversion from 'std::ofstream' (aka 'basic_ofstream<char>') to 'OIIO::ifstream &' (aka 'basic_ifstream<char> &') for 1st argument
OIIO_API void open (OIIO::ifstream &stream, string_view path,

**Comment by lgritz** [comment]
Aha, I think I see what's wrong here. Patch coming soon...

**Comment by lgritz** [comment]
See #1188 for proposed solution (against master; I will backport to 2.1 after it's reviewed and merged).
