### ISSUE TITLE
OSL fails to compile with openimageio-2.2.7.0

### ISSUE THREAD

**Issue by HJarausch** [imageworks/OpenShadingLanguage#1282]
Compiling osl-1.10.10 with openimageio-2.2.7.0 fails with _formatting of non-void pointers is disallowed_.  <br/>The problem arises in **liboslexec/context.cpp**  in lines 100-101   <br/> `            info ("  ShadingContext %p growing heap to %llu",
                  this, (unsigned long long) heap_size_needed);
`   <br/>which tries to format an integer.
### Versions

* OSL 1.10.10: 
* OS: Gentoo Linux 
* openimageio-2.2.7.0

* C++ compiler:  gcc-10.2.1

**Comment by lgritz** [comment]
This was fixed in 1.10.13, released on August 1.
