### ISSUE TITLE
Compilation fails on Windows due to undefined __builtin_ctz call.

### ISSUE THREAD

**Issue by ix-dcourtois** [imageworks/OpenShadingLanguage#1292]
### Problem

OSL (@ c7d77d85080cebcd64739db22f1c570582e27adf) fails to build on Windows due to PR #1276
in `OSL/mask.h`, line 166, `__builtin_ctz` is undefined on MSVC.

I fixed this with the following patch (taken from c7d77d85080cebcd64739db22f1c570582e27adf) but I'm not sure if this is ok.
Maybe the author of the PR (@AlexMWells) could take a look ?

```
diff --git a/src/include/OSL/mask.h b/src/include/OSL/mask.h
index 1580f39e..4b430224 100644
--- a/src/include/OSL/mask.h
+++ b/src/include/OSL/mask.h
@@ -162,6 +162,10 @@ public:
         if (value_width <= 32) {
 #if __INTEL_COMPILER
             return _bit_scan_forward(m_value);
+#elif (defined(_WIN32) || defined(_WIN64))
+            unsigned long index;
+            _BitScanForward(&index, m_value);
+            return static_cast<int>(index);
 #else
             return __builtin_ctz(m_value);
 #endif

```

### Versions

* OSL branch/version: master
* OS: Windows
* C++ compiler:  MSVC 2017
* LLVM version: 11.0
* OIIO version: 2.1.xx

**Comment by lgritz** [comment]
Fix is already submitted: #1291
