### ISSUE TITLE
Confusing error message when standard library header is not found

### ISSUE THREAD

**Issue by laserallan** [imageworks/OpenShadingLanguage#152]
In the file src/master/liboslcomp/oslcomp.cpp:
If the test on line 323  fails:
if (OIIO::Filesystem::exists (path.string())) {

The variable path will not be updated to contain "/stdosl.h" in the end. This makes the error reported on line 339 in the same file confusing since the path it says it can't find doesn't say anything about stdosl.h but only mentioning a missing directory. It makes more sense to explicitly say it's the standard library missing and write the full path to the missing file. 

Off topic:
It's the first time I post here, would you prefer to see a patch here or is this form ok?

**Comment by lgritz** [comment]
I think this is long since fixed.
