### ISSUE TITLE
cmake fails to find IlmBase on Debian; should use pkg-config

### ISSUE THREAD

**Issue by snogglethorpe** [imageworks/OpenShadingLanguage#230]
I tried to compile OpenShadingLanguage on my Debian system, and while the build system apparently has some sort of configuration stuff for IlmBase, it fails on Debian.

I briefly looked at the cmake config stuff for it, in "src/cmake/modules/FindIlmBase.cmake", but it's pretty impenetrable (cmake: confusing), and I couldn't figure out how to fix it, or even how to manually alter the settings so I could specify my setup manually.

IlmBase's pkg-config setup gives the right compiler options to use to find IlmBase:

```
$ pkg-config --cflags IlmBase
-I/usr/include/OpenEXR  
$ pkg-config --libs IlmBase
-lImath -lHalf -lIex -lIlmThread -lpthread  
```

Really, FindIlmBase.cmake should use pkg-config to find what settings to use for IlmBase, as it should yield accurate info for any system which has IlmBase installed.  [It could use the current more adhoc config stuff in the case where pkg-config isn't available, or doesn't know about IlmBase.

[I'm sorry I can't offer much help in changing this, as I don't know cmake.]

**Comment by abergmeier** [comment]
I just opened this pull request for Blender. Maybe you want to merge it into master, too?
https://github.com/Nazg-Gul/OpenShadingLanguage/pull/2

**Comment by ldo** [comment]
There is a fundamental incompatibility between the mindset of `pkg-config` versus CMake. `pkg-config` returns options to be included in compiler and linker command lines for `gcc`, `ld` and tools that are sufficiently compatible with them. CMake, on the other hand, is designed to allow builds on entirely different toolsets, on entirely different platforms.

Thus, CMake wants the actual library file name, not command-line options; it will generate the appropriate command-line options itself.

**Comment by lgritz** [comment]
@abergmeier -- can you submit it to upstream OSL as a pull request? That would make things a lot easier.

**Comment by carldong** [comment]
What is the status? Fedora 23 also has this issue.

**Comment by lgritz** [comment]
I think I have a suitable replacement. Need to test tomorrow at work, then will submit a PR if it works on all the configurations there.

**Comment by lgritz** [comment]
I'm testing this out on the OIIO side first: https://github.com/OpenImageIO/oiio/pull/1346

Much simpler FindOpenEXR.cmake, synthesized from the ideas of other examples on the net that seemed simple. It's still just pure cmake, no pkgconfig. But it's vastly simplified and I hope reasonably foolproof.

If this gets approval there, I'll port to OSL.

**Comment by lgritz** [comment]
Rewrite of FindOpenEXR.cmake has been merged into OIIO (master) and is now proposed on the OSL side here:  https://github.com/imageworks/OpenShadingLanguage/pull/621

If these seem to go smoothly for everybody, I'll backport them to the current releases.

**Comment by lgritz** [comment]
Fixed long ago. Never closed the issue. Closing now.
