### ISSUE TITLE
Returning struct from nested function assertion

### ISSUE THREAD

**Issue by brechtvl** [imageworks/OpenShadingLanguage#233]
Compiling this
```
struct Test { float f; };

shader test()
{
    Test some_function()
    {
        Test a;
        return a;
    }

    Test b = some_function();
}
```

results in src/liboslcomp/typecheck.cpp:1241: Failed assertion '0': Don't know how to decode type code '49'

If some_function is not nested it still gives a compile error but no assertion is hit. I can try to fix this but I'm wondering if I should try to make it throw an error for this case or if returning structs should actually work?

**Comment by lgritz** [comment]
This has been fixed.
