### ISSUE TITLE
ubersurface.oso compile error

### ISSUE THREAD

**Issue by est77** [imageworks/OpenShadingLanguage#241]
When building, from master, on OSX, 10.8:

[ 83%] Generating ubersurface.oso
/usr/local/src/OpenShadingLanguage/src/shaders/ubersurface.osl:150: error: shader parameter 'Texture_' MUST have a default initializer
/usr/local/src/OpenShadingLanguage/src/shaders/ubersurface.osl:150: error: Syntax error: syntax error
FAILED /usr/local/src/OpenShadingLanguage/src/shaders/ubersurface.osl
make[2]: **\* [shaders/ubersurface.oso] Error 1
make[1]: **\* [shaders/CMakeFiles/shaders.dir/all] Error 2
make: **\* [all] Error 2

**Comment by lgritz** [comment]
Long ago fixed, but nobody closed the issue. Closing now.
