### ISSUE TITLE
Non-output function parameters can be modified

### ISSUE THREAD

**Issue by brechtvl** [imageworks/OpenShadingLanguage#269]
From a bug report to the Blender bug tracker by Michel Anders.

```
int refinc(int n)
{
    n = 0; // n is not marked as output so this should be illegal
    n++;   // ditto
    return n;
}

shader test()
{
    int h = 0;
    refinc(h);
    printf("%d\n", h);
}
```

If you run this compile and run shader, it will print `1`, but actually modifying `n` in `refinc` should not be allowed, according to section 4.4 of the specification, so it should give a compile error.

> Parameters to functions are similar to shader parameters, except that they do not permit initializers. A function call must pass values for all formal parameters. Function parameters in Open Shading Language are all passed by reference, and are read-only within the body of the function unless they are also designated as output (in the same manner as output shader parameters).

**Comment by lgritz** [comment]
This was fixed for OSL 2.0. It's a warning now (and an error if you compile with -Werror). Closing.
