### ISSUE TITLE
Updates to build with libc++

### ISSUE THREAD

**Issue by sambler** [imageworks/OpenShadingLanguage#292]
This is in reference to commit 6c568674a5194de43b93b9bad1cd0db41b11016c

I'm only concerned here with the changes in src/CMakeLists.txt.

I understand that these changes are to bypass the use of the gcc extension of std::filebuf having a FILE\* constructor by using boost_wave - is this planned to be a permanent solution or just a temporary fix?

line 129 -- `if (EXISTS "/usr/lib/libc++.dylib" OR OSL_USE_LIBCPP)`

The "OR OSL_USE_LIBCPP" needs to be removed, we are simply defining OSL_SYSTEM_HAS_LIBCPP. The search for libc++ needs to be more flexible. .so or .a suffixes on *nix machines possibly /usr/local/lib for user installed libs. .dll suffix and what locations would this be in on windows? Should the search for libc++ be added to cmake/modules or externalpackages.cmake? Could that lead to OSL_LIBCPP_PATH being user adjustable option?

OSL_USE_LIBCPP needs to be made visible to the user in ccmake or cmake-gui by adding -
`set (OSL_USE_LIBCPP ON CACHE BOOL "Build using libc++ if available")`

The last test that adds -stdlib need expanding - possibly --

```
if (CMAKE_COMPILER_IS_CLANG AND OSL_SYSTEM_HAS_LIBCPP AND OSL_USE_LIBCPP)
    message (STATUS "Using libc++")
    add_definitions ("-stdlib=libc++")
    if (NOT USE_BOOST_WAVE)
        error ("Boost wave needs to be enabled when using libc++")
    endif()
endif ()
```

If boost wave is temporary fix then most if not all of these cmake changes can be removed.

**Comment by lgritz** [comment]
Closing, no longer relevant -- these days we are able to use clang components and no longer need boost wave.
