### ISSUE TITLE
Mistakes in the .pdf docs

### ISSUE THREAD

**Issue by DingTo** [imageworks/OpenShadingLanguage#306]
Hi,
here a collection with mistakes I found in the .pdf docs.

-7.5, Gabor Noise: the "do_filter" point is listed twice. 
-4.1 Shader Types, mention the type "light", but light brings up a compile error. (Unknown shader type: light).

Not a big deal, but nice to fix once.

Cheers,
Thomas

**Comment by ldo** [comment]
I can’t find the issue with “do_filter” in the current docs—looks like that has been fixed.

On page 2 it says “Surface and light shaders are the same thing”. Given this, perhaps it makes sense to omit mention of “light” shader types on page 13.

**Comment by lgritz** [comment]
Fixed now, thanks.
