### ISSUE TITLE
Building fully-static OSL chain with CMake

### ISSUE THREAD

**Issue by mont29** [imageworks/OpenShadingLanguage#311]
Currently, it is very hard to build a full-static OSL. The main reason is that static libs (at least in Linux world, .a) do not embed the static libs they use. So e.g. libOpenImageIO.a holds absolutely no link to IlmImf.a (or .so), neither to libjpeg, etc.

Then, at OSL level, we have to explicitly add to link list all IlmBase, OpenEXR and OIIO (including its dependencies, jpeg, png, etc.)…

For now, I can see thrre ways to handle this:
1) Add a STATIC_LINK_LIBS props, that should be filled by builders who want to compile against static Openexr/OIIO.
2) Add all libs from OIIO cmake to OSL cmake, and use them in case of static building. This is perhaps the easiest automatic solution, but it would add many things to OSL cmake just to support that (rather specific) build scenario, not sure you guys would like that.
3) Make OIIO cmake output in a text file a complete list of paths and libs it used to build, which could be automatically read by OSL cmake in case of static linking.

Solution 3) is my preferred one, even though slightly hacky, it should not add too much overhead to neither OIIO nor OSL cmake, and still allows for easy scripted build of the whole tool chain. Thoughts?

Regards,
Bastien

**Comment by lgritz** [comment]
Closing. Very old and possibly no longer relevant. Re-file if it's still a problem.
