### ISSUE TITLE
init argument with empty array

### ISSUE THREAD

**Issue by maxliani** [imageworks/OpenShadingLanguage#335]
Hello,
I'm experiemnting with a OSL and a simple summation shader gives me compilation errors.

This compiles fine:

shader summation (
  vector _input[1] = {0},
  output vector _output = 0
  )
{
  vector s = 0;
  for (int i = 0; i < arraylength(_input); ++i)
    s += _input[i];
  _output = s;
}

This errors out with: layers.osl:2: error: Too many initializers for a 'vector[]'

shader layers (
  vector _input[] = {0},
  output vector _output = 0
  )
{...}

This errors out with: layers.osl:2: error: Syntax error: syntax error

shader layers (
  vector _input[],
  output vector _output = 0
  )
{...}

This errors out with: layers.osl:2: error: Syntax error: syntax error

shader layers (
  vector _input[] = {},
  output vector _output = 0
  )
{...}

I can't figure out what is the correct way to initialize the agument as empty array.

**Comment by Dargish** [comment]
Hi, I'm having the exact same issue as Max when trying to implement a ramp shader with an undefined length array of floats being passed through.

The documentation seems to indicate that this should work:

> There are two circumstances when arrays do not need to have a declared length — an array parameter to a function, and a shader parameter that is an array

Has this fix been committed yet? I'm trying version 1.6.9 with no luck.

If not then I will go with your suggestion Larry of using a maximum length and a separate value for the number of elements passed through.

**Comment by luisbarrancos** [comment]
I'm having the same issue here. It would be great to have this without having to use the workaround.

**Comment by lgritz** [comment]
I believe this was long-ago fixed at some point in the 1.6 releases. Closing.
