### ISSUE TITLE
Strict overflow issue with 1.4.4 on Ubuntu 12.04

### ISSUE THREAD

**Issue by nyue** [imageworks/OpenShadingLanguage#349]
Whilst attempting the build the 1.4.4 release on Ubuntu 12.04, I encountered the following problem.

/home/nicholas/projects/OpenShadingLanguage/OpenShadingLanguage_git/src/liboslexec/oslexec_pvt.h: In function ‘int OSL::pvt::constfold_getattribute(OSL::pvt::RuntimeOptimizer&, int)’:
/home/nicholas/projects/OpenShadingLanguage/OpenShadingLanguage_git/src/liboslexec/oslexec_pvt.h:1468:64: error: assuming signed overflow does not occur when assuming that (X - c) <= X is always true [-Werror=strict-overflow]
/home/nicholas/projects/OpenShadingLanguage/OpenShadingLanguage_git/src/liboslexec/oslexec_pvt.h:1468:64: error: assuming signed overflow does not occur when assuming that (X - c) <= X is always true [-Werror=strict-overflow]
cc1plus: all warnings being treated as errors
make[2]: **\* [src/liboslexec/CMakeFiles/oslexec.dir/constfold.cpp.o] Error 1
make[1]: **\* [src/liboslexec/CMakeFiles/oslexec.dir/all] Error 2
make: **\* [all] Error 2

**Comment by lgritz** [comment]
Closing, so very old. If this is still a problem on today's OSL, please re-file.
