### ISSUE TITLE
Pow(color, color) not supported in code (but is is in docs)

### ISSUE THREAD

**Issue by reinhrst** [imageworks/OpenShadingLanguage#402]
The OSL spec (1.4 and 1.5) specify that `pow(type  x, type y)` is allowed (where type can be a color/vector/point/normal/float). I only find the second signature `pow(type x, float y)` to be supported by the compiler. This is supported by the code in llvm_instance.cpp:

```
    BINARY_OP_IMPL(pow),
[...]
    "osl_pow_vvf", "xXXf",
    "osl_pow_dvdvdf", "xXXX",
    "osl_pow_dvvdf", "xXXX",
    "osl_pow_dvdvf", "xXXf",
```

Either the specification or the implementation contains a bug here.

**Comment by lgritz** [comment]
This was fixed by #665
