### ISSUE TITLE
Runtime static initialization error in BackendLLVM::ShaderGlobalNameToIndex

### ISSUE THREAD

**Issue by AdrienHerubel** [imageworks/OpenShadingLanguage#406]
When executing an OSL shader in very particular conditions (On Windows, with oslexec.dll on a slow disk) I randomly run into the assert  :
ASSERT (sg_index >= 0); in BackendLLVM::llvm_global_symbol_ptr
The problem is that the symbol here actually is a global OSL symbol (generally 'u' in my test case).

The bug might come from the fact that the static 'fields' array in BackendLLVM::ShaderGlobalNameToIndex is initialized at runtime. When the function is called by multiple threads, given a particular set of conditions, a thread can consider the array as empty. 

The assert is not triggered any more when the 'fields' array is initialized outside of the function, in an anonymous namespace.

**Comment by lgritz** [comment]
It looks like the advice from this issue (moving the `fields` array from inside the function to a static in an anonymous namespace) was implemented long ago. Closing.
