### ISSUE TITLE
externalpackages.cmake does not find shared LLVM libs

### ISSUE THREAD

**Issue by Shootfast** [imageworks/OpenShadingLanguage#460]
Hi, I have my copy of LLVM 3.4.2 built with shared libraries, and with the current CMake setup in OSL, the LLVM packages are not found.

On the following lines, LLVM is looking for a library named libLLVM-3.4.2.so, which does not exist. 
[link](https://github.com/imageworks/OpenShadingLanguage/blob/master/src/cmake/externalpackages.cmake#L175-L179)

This entire setup is at odds with the recommended way of finding / configuring LLVM.
http://llvm.org/docs/CMake.html#embedding-llvm-in-your-project

At the moment, I have worked around this, by applying the following patch (which does similar to the code path when LLVM_STATIC is defined on [Line 206](https://github.com/imageworks/OpenShadingLanguage/blob/master/src/cmake/externalpackages.cmake#L206) but this is also quite wrong.

```
diff -Nur OpenShadingLanguage-Release-1.5.10_orig/src/cmake/externalpackages.cmake OpenShadingLanguage-Release-1.5.10/src/cmake/externalpackages.cmake
--- OpenShadingLanguage-Release-1.5.10_orig/src/cmake/externalpackages.cmake    2015-01-19 20:05:46.818128241 +0000
+++ OpenShadingLanguage-Release-1.5.10/src/cmake/externalpackages.cmake 2015-01-19 21:24:44.195788795 +0000
@@ -174,11 +174,11 @@
   execute_process (COMMAND ${LLVM_CONFIG} --includedir
        OUTPUT_VARIABLE LLVM_INCLUDES
        OUTPUT_STRIP_TRAILING_WHITESPACE)
+  execute_process (COMMAND ${LLVM_CONFIG} --libs
+       OUTPUT_VARIABLE LLVM_LIBRARY
+       OUTPUT_STRIP_TRAILING_WHITESPACE)
 endif()

-find_library ( LLVM_LIBRARY
-               NAMES LLVM-${LLVM_VERSION}
-               PATHS ${LLVM_LIB_DIR})
 message (STATUS "LLVM version  = ${LLVM_VERSION}")
 message (STATUS "LLVM dir      = ${LLVM_DIRECTORY}")
```

Cheers,
Mark

**Comment by lgritz** [comment]
That page specifically says LLVM 3.5 and beyond (I'm on 3.4 because of gcc version constraints). I'm less clear on what to do with older LLVM or to account for the fact that different sites or products building OSL may not all be on the same version of LLVM.

Why do you say that your proposal is quite wrong? Looks reasonable to me (though I haven't tried it out on my end).

**Comment by Shootfast** [comment]
> That page specifically says LLVM 3.5 and beyond 

I've been using the linked CMake code on LLVM 3.2 and 3.4 reliably (at least on linux).

> I'm on 3.4 because of gcc version constraints

Ditto, but I'll hopefully get a build to test with that soon too

> Why do you say that your proposal is quite wrong?

Only that I'm slamming in every LLVM library, not neccessarily the ones required.

The llvm-config tool is a little broken too. `llvm-config --libfiles` still returns the static libs, even if they aren't built, though I havn't investigated that on 3.5 yet, but I'll be reporting those issues upstream too.

Cheers,
Mark

**Comment by lgritz** [comment]
Closing this stale issue, which references very old OSL and LLVM versions. I think the externalpackages.cmake and FindLLVM have changed a lot since then, so it may be long since solved. If it's still a problem, please re-file.
