### ISSUE TITLE
RB-1.5 -- ISO C++ 2011 error

### ISSUE THREAD

**Issue by ReubenM** [imageworks/OpenShadingLanguage#469]
I'm trying to build RB-1.5 and keep running into this error:

Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/llvm_util.cpp.o
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/include/g++-v4/type_traits:35:0,
                 from /usr/include/llvm/Support/MathExtras.h:21,
                 from /usr/include/llvm/ADT/SmallVector.h:20,
                 from /usr/include/llvm/ADT/ArrayRef.h:14,
                 from /usr/include/llvm/ADT/APInt.h:19,
                 from /usr/include/llvm/ADT/APFloat.h:20,
                 from /usr/include/llvm/IR/Constants.h:24,
                 from /home/reuben/code/OpenShadingLanguage/src/liboslexec/llvm_util.cpp:41:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/include/g++-v4/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

Now if I add the -std=c++11 to the CXXFLAGS in flags.make for that subdirectory, it continues but fails later on with:

Building CXX object src/liboslexec/CMakeFiles/oslexec.dir/shadingsys.cpp.o
In file included from src/liboslexec/shadingsys.cpp:49:0:
/usr/include/OpenImageIO/fmath.h:1301:13: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration using std::isnan;

The OpenImageIO/fmath.h is from openimageio-1.4.16

gcc-4.9.2
llvm-3.5.1

**Comment by lgritz** [comment]
May I suggest trying to upgrade to OIIO 1.5? A number of fixes to fmath.h were made to allow better compatibility with newer compilers and with C++11 conventions.

**Comment by ReubenM** [comment]
I actually started initially with OIIO 1.5.12, but that is a can of worms also.

The first error is:

llvm_ops.cpp:106:13: error: no member named 'safe_asinf' in namespace 'OpenImageIO::v1_5'; did you mean 'safe_asin'?

So I changed all references of 'safe_asinf' to 'safe_asin' but it then run into errors reguarding undefined members:

llvm_ops.cpp:1269:10: error: no member named 'nchannels' in 'OpenImageIO::v1_5::TextureOpt'
    opt->nchannels = chans;
    ~~~  ^
llvm_ops.cpp:1271:10: error: no member named 'dresultds' in 'OpenImageIO::v1_5::TextureOpt'
    opt->dresultds = dresultdx ? dresultds : NULL;

**Comment by lgritz** [comment]
Something is out of sync here.

Let's start with something we know works: OIIO 1.5 top of RB-1.5 tree, or the latest tag (Release-1.5.12), or master, and OSL current top of master tree.

**Comment by ReubenM** [comment]
I was able to compile OSL master against OIIO tag 1.5.12. (As long as MCJIT is disabled)

**Comment by lgritz** [comment]
Which LLVM? Can you confirm that you can get a fully working build with the following combination:

* OSL master, disable MCJIT
* OIIO >= 1.5.12
* LLVM 3.5
* gcc 4.9, -std=c++11

**Comment by ReubenM** [comment]
Yes.

    OSL master, disable MCJIT
    OIIO >= 1.5.12
    LLVM 3.5.1
    gcc 4.9.2, -std=c++11

**Comment by lgritz** [comment]
Outstanding. That's good to know.

Now, the big gotcha is that, IIRC, LLVM 3.5 is the last one with the old JIT. For 3.6 and beyond, it's *only* MCJIT, and since release of 3.6 is imminent, I guess I'm going to have to get that working soon.

I'm going to close this issue since you seem to be unstuck now.
