### ISSUE TITLE
closure color functions in OSL 1.6

### ISSUE THREAD

**Issue by ghost** [imageworks/OpenShadingLanguage#558]
What happened to `bssrdf_cubic`, `bssrdf_gaussian`, `hair_R`, `hair_TRT`, `hair_TT` functions in OSL 1.6 (corresponding functions in current `stdosl.h`?

**Comment by fpsunflower** [comment]
These were closure prototypes from SPI's renderer - not part of the official OSL spec. We removed them to avoid confusion.

**Comment by lgritz** [comment]
I think the question here was answered. Closing.
