### ISSUE TITLE
external CMAKE file gives wrong error message when C++11 is not used with LLVM3.5

### ISSUE THREAD

**Issue by tschiex** [imageworks/OpenShadingLanguage#563]
if (LLVM_VERSION VERSION_GREATER 3.4.9 AND NOT OSL_BUILD_CPP11)
    message (FATAL_ERROR "LLVM ${LLVM_VERSION} requires C++11. You must build with USE_CPP11=1.")

should be

if (LLVM_VERSION VERSION_GREATER 3.4.9 AND NOT OSL_BUILD_CPP11)
    message (FATAL_ERROR "LLVM ${LLVM_VERSION} requires C++11. You must build with OSL_BUILD_CPP11=1.")

**Comment by lgritz** [comment]
Fixed by #634
