### ISSUE TITLE
CMakeLists.txt : incorrect variable name

### ISSUE THREAD

**Issue by jeannoeldot** [imageworks/OpenShadingLanguage#570]
In CMakeLists.txt, lines 257, 258, 262 and 280, the variable names is OIIO_BUILD_CPP11, OIIO_BUILD_CPP14 and "-DOIIO_NO_SSE = 1" instead of OSL_BUILD_CPP11, OSL_BUILD_CPP14 and "-DOSL_NO_SSE = 1"

Thank you for your work and for reading

**Comment by lgritz** [comment]
Oops, you are quite right! 

A typo obviously resulting from carelessness in copying those sections of code between OIIO and OSL.

Fix in #573

**Comment by lgritz** [comment]
The OIIO_NO_SSE part, I believe, is correct, because that's just straight-up using the simd.h from OIIO.
