### ISSUE TITLE
OSL IL Spec

### ISSUE THREAD

**Issue by adityaatluri** [imageworks/OpenShadingLanguage#577]
Hi,
Where can I find OSL IL Spec?

**Comment by lgritz** [comment]
If by "IL" you mean the intermediate representation stored in .oso files, there is no written spec for it. It should be relatively self-explanatory, but feel free to ask any specific questions and I'll try to answer.

I think in general,  "issues" on GitHub should be for things reasonably suspected to be bugs. It's only read by people closely following the code development. The UX of "issues" -- ideas such as assignees, milestones, closing, etc. -- is a good match for reporting a reproducible bug, but a poor match for inquiries.

General "questions" about the language or its implementation, or other open-ended discussions, are probably better asked on the osl-dev mail list, where it is more likely to find a wider audience (who could benefit from the discussion, as well as potentially answer more quickly than I can get to it).
