### ISSUE TITLE
`make doxygen` no longer needed(?), should be removed

### ISSUE THREAD

**Issue by MrMormon** [imageworks/OpenShadingLanguage#591]
I'd make a pull request but I'm rusty on makefile-ese.

**Comment by lgritz** [comment]
Is it really a problem? 

I have fallen out of love with Doxygen, so haven't tried this in ages. What does it do, how broken is it?

I guess it's possible that we want to let people build Doxygen docs if they really want to. What's the harm in leaving it there, and fixing it if and when anybody complains that it doesn't work well?

**Comment by MrMormon** [comment]
It looks for a doxygen file that isn't there. It does absolutely nothing but complain, so there's nothing to say works 'well'.

**Comment by lgritz** [comment]
Oh, in that case, I'll remove it from the Makefile. I should have checked that it was functional before replying.
