### ISSUE TITLE
Scripts to install dependencies

### ISSUE THREAD

**Issue by lgritz** [imageworks/OpenShadingLanguage#593]
Redirected from #592.

@MrMormon says:

Could this lead to a build script in the future for Unix-like users?

Cmake still requires manual setup of LLVM and environment variables.

The Julia language downloads external dependencies in its make script, as an example.

A user-friendly alternative could be pre-compiled binaries, which the Rust language downloads with .sh scripts (except for Windows of course).

Both of those languages are favorites of mine in the general-purpose area, not least because they use LLVM as their sole backend.

**Comment by lgritz** [comment]
@MrMormon: I got part way there with the #592 Travis work, which includes `src/build-scripts/install_homebrew_deps.bash` which in addition to being called by the Travis scripts actually should work just fine completely standalone to install (via Homebrew, only on OSX) most of the dependencies you need to build OSL. We could similarly add scripts to this directory that would work for other platforms and package managers. I just need somebody to write, test, and submit PR's, and I'll happily merge.

Also in the same directory `build_openexr.bash` downloads and builds IlmBase and OpenEXR, and `build_openimageio.bash` downloads and builds OIIO. I'm not sure if that's the best approach (a separate script/download), or if it's better to simply make those "Git submodules" which the build scripts themselves will only recursively clone and build if no system versions are found.

In general, I really like this idea, but I will need help. I can do all the work for OSX/Homebrew myself. For RedHat-like Linux, I can do the parts that build from source and/or git submodules, but it's awkward for me to install packages. I don't have much ability to write or test for other platforms or package managers. But like I said, I would jump at the chance to merge others' efforts in this area, just write an appropriate src/build-scripts entry for your platform of choice and submit a PR. We can also make the make/cmake detect that it should run certain scripts if the packages aren't installed, or just print a message instructing people to do it by hand.

For packages best built from source, I'm interesting in anybody's opinions about making them git submodules versus having a script that does a git clone and builds from scratch. Of course, in either case, it would only happen if the packages weren't already detected on the system, so for most people there would be no extra build-time expense.

**Comment by MrMormon** [comment]
Thanks for your work so far. I can see what needs to be done for Linuxbrew.

**Comment by lgritz** [comment]
I do agree that it would be nice to have a build-time option for OSL build itself to download and build any missing dependencies, and I would be very happy to entertain PRs that accomplish this (altogether, or even one important dependency at a time). But I don't think we need this issue ticket to remain open in order to remember that such a PR would be welcome. Closing.
