### ISSUE TITLE
Empty .oso Output File Names

### ISSUE THREAD

**Issue by ldo** [imageworks/OpenShadingLanguage#599]
I’m hitting a problem where all the .osl files are being compiled to the output name “.oso” (that is, empty apart from the extension). It seems the default output filename is empty. The following is a workaround:

    diff --git a/src/shaders/CMakeLists.txt b/src/shaders/CMakeLists.txt
    index 487efbc..94b9138 100644
    --- a/src/shaders/CMakeLists.txt
    +++ b/src/shaders/CMakeLists.txt
    @@ -27,7 +27,7 @@ macro (osl_compile oslsrc objlist headers)
             message (STATUS "cmd: ${CMAKE_CURRENT_BINARY_DIR}/../oslc/oslc ${oslsrc}")
         endif ()
         add_custom_command (OUTPUT ${osofile}
    -        COMMAND "${CMAKE_CURRENT_BINARY_DIR}/../oslc/oslc" -q ${oslsrc}
    +        COMMAND "${CMAKE_CURRENT_BINARY_DIR}/../oslc/oslc" -o ${osofile} ${oslsrc}
             MAIN_DEPENDENCY ${oslsrc}
             DEPENDS ${${headers}} ${oslsrc} "${CMAKE_CURRENT_BINARY_DIR}/stdosl.h" "${CMAKE_CURRENT_BINARY_DIR}/../oslc/oslc"
             WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})

**Comment by lgritz** [comment]
I have no objections to that change, it merely makes explicit the name of the output file.

But I'm confused because the output file should certainly be the same either way.

Before I make this change, would you mind changing that line to 

    COMMAND "${CMAKE_CURRENT_BINARY_DIR}/../oslc/oslc" ${oslsrc}

that is, please don't use the `-o` quite yet, but remove the `-q` (quiet mode), and then try again with a fresh compile and let's see if there's any output or error messages that might give us a clue about what's going on.

Do you build by invoking cmake directly, or do you use the 'make' wrapper?

**Comment by lgritz** [comment]
Did you get a chance to try this?

**Comment by ldo** [comment]
Sorry, haven’t had a chance yet.

But I note that Blender includes [this patch](https://developer.blender.org/diffusion/B/browse/master/build_files/build_environment/install_deps_patches/osl.patch) to work around exactly the same problem.

**Comment by lgritz** [comment]
The patch is fine, but before we merge it and then forget all about it, I'd like to make sure we understand why it's not already doing that with the default arguments, in case it's just masking a problem that will pop up in another context.

**Comment by ldo** [comment]
You’ll be pleased to know, I am now building the current `release` branch just fine, without any special patches. As per your advice, my build command is

    make -j$(nproc) LLVM_VERSION=3.5 USE_CPP11=1 ILMBASE_HOME=/usr/local STOP_ON_WARNING=0

**Comment by lgritz** [comment]
So, do you want to close and abandon this issue? Or is it something we should still look into?

Was it an older branch where you were originally having the problem? Perhaps whatever it was, it's long since fixed. If it doesn't afflict the 1.6 branch (or master), I think we should just let it go.

**Comment by ldo** [comment]
I have no problem building the current release branch any more.

When I try building the previous commit that, according to my notes, I was having the trouble with, it now fails with “m_perthread_info” being undefined. I think this member comes from OpenImageIO.

Perhaps it is down to the fact that I have updated my OpenImageIO installation. Do you think that could have been a factor in the .oso-naming bug?

**Comment by lgritz** [comment]
I don't see why it would be related to oso naming, but that would certainly indicate a mismatch of OIIO and OSL versions. 

Well, if this is no longer an ongoing problem for you with release/RB-1.6 or with master, let's close the issue.

**Comment by ldo** [comment]
Done.

**Comment by ldo** [comment]
Just for your info, the problem with .oso naming recurred on another machine. I tracked it down to a (likely broken) OpenImageIO 1.6.3 installation. Copying the known-good OIIO 1.6.8 installation from the other machine fixed the problem.
