### ISSUE TITLE
Meaning Of “op=”?

### ISSUE THREAD

**Issue by ldo** [imageworks/OpenShadingLanguage#610]
On page 36 of the language spec, you say “In general, var OP= expr is allowed only if var = var OP expr is allowed, and means exactly the same thing”. I haven’t checked this as yet, but if you follow behaviour consistent with C, then this is most certainly not true. For example, consider the difference between

    a = a * b + c

and

    a *= b + c

Even saying “var OP= expr” is equivalent to “var = var OP (expr)” is not strictly correct, as you can see from the output of the following C program:

    #include <stdio.h>

    int main(void)
      {
        const int numer = 3;
        const int denom = 2;
        int a = numer, b = numer;
        a *= numer / denom;
        b = b * numer / denom;
        fprintf(stdout, "a = %d, b = %d\n", a, b);
        return
            0;
      } /*main*/

In sum, assuming that _int_ / _int_ is integer division as it is in C, then the doc is wrong.

**Comment by lgritz** [comment]
I think you might be confused about an "expression" (in the parsing sense).

In `a = a*b + c`, the `b+c` is not an expression with C's (or OSL's) parsing rules, which has higher precedence for multiplication. In that snippet of code, `a*b` is an expression, and `(a*b)+c` is an expression, but `b+c` is not parsed as a unit and is not an expression (not in that statement, anyway).

**Comment by ldo** [comment]
OK. Makes sense.
