### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ldo** [imageworks/OpenShadingLanguage#611]
Markup correction:

    diff --git a/src/doc/languagespec.tex b/src/doc/languagespec.tex
    index fe2276e..5cc3a50 100644
    --- a/src/doc/languagespec.tex
    +++ b/src/doc/languagespec.tex
    @@ -3728,7 +3728,7 @@ expected.
     \indexapi{format()}
     The {\cf format} function works similarly to {\cf printf}, except that
     instead of printing the results, it returns the formatted text as a
    -\string.
    +{\cf string}.
     \apiend

     \apiitem{void {\ce error} (string fmt, ...) \\

**Comment by lgritz** [comment]
Thanks!

Fixed.
