### ISSUE TITLE
Another Little Typo

### ISSUE THREAD

**Issue by ldo** [imageworks/OpenShadingLanguage#614]
diff --git a/src/doc/languagespec.tex b/src/doc/languagespec.tex
    index 08e302f..f5dd483 100644
    --- a/src/doc/languagespec.tex
    +++ b/src/doc/languagespec.tex
    @@ -3417,7 +3417,7 @@ derivatives.  Gabor noise allows several optional parameters to the
     "direction", <vector>}
     \vspace{12pt}
     If {\cf anisotropic} is 0 (the default), Gabor noise
    -will be isotropic.  If {\cf anisotripic} is 1, the Gabor noise will
    +will be isotropic.  If {\cf anisotropic} is 1, the Gabor noise will
     be anisotropic with the 3D frequency given by the {\cf direction} 
     vector (which defaults to {\cf (1,0,0)}).  If {\cf anisotropic} is
     2, a hybrid mode will be used which is anisotropic along the

**Comment by ldo** [comment]
And another:
    diff --git a/src/doc/languagespec.tex b/src/doc/languagespec.tex
    index 1599a85..7ce8082 100644
    --- a/src/doc/languagespec.tex
    +++ b/src/doc/languagespec.tex
    @@ -4526,7 +4526,7 @@ the previous function.
     \apiend


    -\apiitem{\colorclosure\ \colorclosure\ {\ce reflection} (normal N, float eta)}
    +\apiitem{\colorclosure\ {\ce reflection} (normal N, float eta)}
     \indexapi{reflection()}

     Returns a \colorclosure that represents sharp mirror-like reflection

**Comment by lgritz** [comment]
Thanks!

I've incorporated these fixes into the docs.
