### ISSUE TITLE
Repo description points to old Google code svn

### ISSUE THREAD

**Issue by MrMormon** [imageworks/OpenShadingLanguage#616]

**Comment by lgritz** [comment]
"Repo description". Where?

**Comment by MrMormon** [comment]
```
Advanced shading language for production GI renderers http://code.google.com/p/openshadinglanguage/
```
https://github.com/imageworks/OpenShadingLanguage

**Comment by lgritz** [comment]
Aha, thanks! Funny, nobody has noticed that for a long time.

In addition, I sent mail to the Google Code people to get that repo shut down and redirected to our GitHub page.
