### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ldo** [imageworks/OpenShadingLanguage#622]
diff --git a/src/doc/languagespec.tex b/src/doc/languagespec.tex
    index 56296f5..33ce277 100644
    --- a/src/doc/languagespec.tex
    +++ b/src/doc/languagespec.tex
    @@ -4269,7 +4269,7 @@ given {\cf data} arrays.  If the optional {\cf sort} parameter is present
     and is nonzero, the ordering of the points
     found will be sorted by distance from {\cf pos}, from closest to farthest;
     otherwise, the results are guaranteed to be the {\cf maxpoints} closest
    -to {\cf pos}, but not necessarily softed by distance (this may be
    +to {\cf pos}, but not necessarily sorted by distance (this may be
     faster for some implementations than when sorted results are
     required).  The return value is the number of points returned, ranging
     from 0 (nothing found in the neighborhood) to the lesser of {\cf maxpoints}

I’m not systematically looking for these, I just come across them as I look things up...

**Comment by ldo** [comment]
And another:

    diff --git a/src/doc/languagespec.tex b/src/doc/languagespec.tex
    index 56296f5..056ddab 100644
    --- a/src/doc/languagespec.tex
    +++ b/src/doc/languagespec.tex
    @@ -2573,7 +2573,7 @@ loop:

     \indexapi{for}
     As in C++, a {\cf for} loop's initialization may contain variable
    -declarations and initializations, which are scoped locally to {\cf for}
    +declarations and initializations, which are scoped locally to the {\cf for}
     loop itself.  For example,

     \begin{code}

**Comment by lgritz** [comment]
Fixed, thanks
