### ISSUE TITLE
Missing/Incomplete Explanation Of Ps Global?

### ISSUE THREAD

**Issue by ldo** [imageworks/OpenShadingLanguage#623]
`Ps` is listed in one table, but not the other. Also fix a typo and missing horizontal line. Feel free to correct the added table entry. :)

    diff --git a/src/doc/languagespec.tex b/src/doc/languagespec.tex
    index 56296f5..4480719 100644
    --- a/src/doc/languagespec.tex
    +++ b/src/doc/languagespec.tex
    @@ -2656,9 +2656,9 @@ P/\partial u$ and $\partial P/\partial v$ tangent to the surface at \P.  \\
     %         {\cf Pl}). \\
     %\hline
     %\color\ {\ce Cl} & Incoming light color at P. \\
    -%\hline
    +\hline
     \point\ {\ce Ps} & Position at which the light is being queried 
    -    (currently only used for light attentuation shaders) \\
    +    (currently only used for light attenuation shaders) \\
     %\\
     %\hline
     %\normal\ {\ce Ns} & Axis about which the light is being queried
    @@ -2729,6 +2729,7 @@ P/\partial u$ and $\partial P/\partial v$ tangent to the surface at \P.  \\
     {\cf Ng}      & R     & R  &    \\
     {\cf dPdu}    & R     & R  &    \\
     {\cf dPdv}    & R     & R  &    \\
    +{\cf Ps}      &       &    & R   \\
     {\cf u, v}    & R     & R  & R   \\
     {\cf time}    & R     & R  & R       \\
     {\cf dtime}   & R     & R  & R       \\

**Comment by lgritz** [comment]
Fixed, thanks
