### ISSUE TITLE
Something missing from src/doc/Makefile?

### ISSUE THREAD

**Issue by ldo** [imageworks/OpenShadingLanguage#625]
When I try to do a `make` in the `src/doc` subdirectory, I get the error

```
make: *** No rule to make target 'languagespec.aux', needed by 'languagespec.pdf'.  Stop.
```

The Makefile rule also mentions `macros.aux`, which is similarly missing. Perhaps `languagespec.aux` should be `languagespec.tex`, and similarly `macros.aux` should be `macros.tex`?

**Comment by ldo** [comment]
Here’s the patch I made to `src/doc/Makefile` to successfully generate `languagespec.pdf` (albeit without the index):

    diff --git a/src/doc/Makefile b/src/doc/Makefile
    index d5ed1a9..b14b12a 100644
    --- a/src/doc/Makefile
    +++ b/src/doc/Makefile
    @@ -6,7 +6,7 @@ all: languagespec.pdf


     # document making rule: use pdflatex
    -languagespec.pdf: *.tex languagespec.aux macros.aux Figures/*.pdf Figures/*png
    +languagespec.pdf: *.tex Figures/*.pdf Figures/*png
        pdflatex ${PDFLATEX_FLAGS} languagespec.tex

Should we also mention we need (on Debian and derivatives) the `latex2html` package to provide `html.sty`, and `texlive-science` to provide `algorithm.sty`?

**Comment by ldo** [comment]
Here is an updated patch for `src/doc/Makefile` that correctly builds `languagespec.pdf` with or without an index, and also adds a `clean` target.

    diff --git a/src/doc/Makefile b/src/doc/Makefile
    index d5ed1a9..23a0205 100644
    --- a/src/doc/Makefile
    +++ b/src/doc/Makefile
    @@ -6,7 +6,7 @@ all: languagespec.pdf


     # document making rule: use pdflatex
    -languagespec.pdf: *.tex languagespec.aux macros.aux Figures/*.pdf Figures/*png
    +languagespec.pdf: *.tex Figures/*.pdf Figures/*png
        pdflatex ${PDFLATEX_FLAGS} languagespec.tex


    @@ -16,7 +16,13 @@ index: languagespec_index

     languagespec_index:
        pdflatex ${PDFLATEX_FLAGS} languagespec.tex
    -   pdflatex ${PDFLATEX_FLAGS} languagespec.tex
        makeindex languagespec
    -   pdflatex ${PDFLATEX_FLAGS} languagespec.tex
    +   pdflatex ${PDFLATEX_FLAGS} languagespec.tex languagespec.aux macros.aux
    +   pdflatex ${PDFLATEX_FLAGS} languagespec.tex languagespec.aux macros.aux languagespec.toc
    +
    +clean:
    +   rm -f languagespec.aux languagespec.idx languagespec.ilg languagespec.ind languagespec.log
    +   rm -f languagespec.out languagespec.pdf languagespec.toc macros.aux
    +

    +.PHONY: clean

**Comment by ldo** [comment]
Or, if you prefer a patch file you can just download and apply:

[make-languagespec.patch.txt](https://github.com/imageworks/OpenShadingLanguage/files/145930/make-languagespec.patch.txt)

**Comment by lgritz** [comment]
Is there a reason you aren't just submitting it as a pull request?

**Comment by ldo** [comment]
Yes.

**Comment by lgritz** [comment]
Closing. I will incorporate these suggestions.
