### ISSUE TITLE
liboslcomp in multiple threads may use null oslcompiler instance

### ISSUE THREAD

**Issue by markfinal** [imageworks/OpenShadingLanguage#654]
Discovered this while using 1.7.2.

`OSLCompilerImpl::osl_parse_buffer`

https://github.com/imageworks/OpenShadingLanguage/blob/master/src/liboslcomp/osllex.l#L333-L345

has a mutex that guards setting the pointer `oslcompiler` to a copy of the compiler.

When there are multiple threads running this code, the mutex blocks each of them until `osl_parse_buffer`exits.

However, this line is unguarded by the mutex

https://github.com/imageworks/OpenShadingLanguage/blob/master/src/liboslcomp/oslcomp.cpp#L515

which will be invoked by any thread that has finished running `osl_parse_buffer`, then nullifies `oslcompiler`, (potentially) causing a subsequent thread unblocked from the mutex to fail because the pointer is now null.

I personally saw a crash with a variety of different stack traces, but all with a null `oslcompiler`.

**Comment by lgritz** [comment]
Sorry for the inexcusably long delay in noticing this issue. I believe you are right. I will prepare a fix for this.
