### ISSUE TITLE
is faceforward() supported?

### ISSUE THREAD

**Issue by sfriedmapixar** [imageworks/OpenShadingLanguage#661]
From this comment
- In OSL, N is already facing forward and normalized.

in the OSL dev forum post here:

https://groups.google.com/forum/#!searchin/osl-dev/faceforward%7Csort:relevance/osl-dev/zNvxAsGcYX0/r1JS82V2kDQJ

I'm assuming that it's not supported, and possibly not needed.  However, the compiler seems to accept it and we get the confusing message:

Parsing shader "Velvet": instruction "faceforward" is not known. Maybe compiled with a too-new oslc?

because the compiler puts a faceforward shadeop in the .oso, but it's not in the table setup in 
shading_system_setup_op_descriptors.

**Comment by lgritz** [comment]
I believe this was fixed long ago by #759
