### ISSUE TITLE
texture() parameters optimization broken

### ISSUE THREAD

**Issue by 1-Olivier** [imageworks/OpenShadingLanguage#670]
There is a bug with (at least) the "swidth" and "twidth" parameters of the texture() shadeop. If they are set from a parameter and that parameter has a default or set value of 1, any connection to the parameter is ignored. It looks somewhat like there is an optimizer which pre-fills the texture opts and is not aware of connections. It is easy enough to work around by making the default 1.000001 in the shader.

I'm attaching a test case for testrender. It is a simple ramp of the filter width over the image so the texture should be sharp at the top and blurry at the bottom. You can use any texture you have lying around with some detail. Uncomment the Parameter in the xml to see what it should look like without the bug. It is broken in 1.7.2 and in the current git head.

[OSL_width_connection.tar.gz](https://github.com/imageworks/OpenShadingLanguage/files/480394/OSL_width_connection.tar.gz)

**Comment by lgritz** [comment]
Aha, you are quite right. Working on a fix...

**Comment by lgritz** [comment]
Fix proposed in #671

**Comment by lgritz** [comment]
The fix for this has been merged into master and RB-1.7.

**Comment by 1-Olivier** [comment]
Thanks. It works great and also fixes the other parameters.
