### ISSUE TITLE
OSL testshade Output Cout not found, skipping.

### ISSUE THREAD

**Issue by ainaerco** [imageworks/OpenShadingLanguage#672]
Hello,
I built OSL from master on Windows, I'm using LLVM 3.5.2 as dependency.
For some reason I can't render any test with testshade that suppose to output image. 
It's complaining that:
Output Cout not found, skipping.
Though render-background with testrender is going through.
Then I tried testshade with checkerboard.osl (from render-background) and it's also complaining.
Expr -o result out.tif -expr 'result=color(u,v,0)' also not working.
Can you suggest anything? Thank you in advance.

**Comment by lgritz** [comment]
Apologies for not seeing this and responding as soon as it was filed.

But in any case, we never replied and the OP never reminded us, so I'm going to assume they probably found the solution (and in addition, it involves long-obsolete versions of OSL and LLVM).

Closing.
