### ISSUE TITLE
Variable names as a function crashes oslc

### ISSUE THREAD

**Issue by Nazg-Gul** [imageworks/OpenShadingLanguage#681]
Hi,

Originally was reported to the Blender's bug tracker [1] but this issue can be reproduced with the current oslc (compiled from 5c8c973).

Easy to reproduce:

Create test.osl with the following content:

```
void bug(float cos){cos(1);} 
shader test(){}
```

and try to compile it using oslc.

[1] https://developer.blender.org/T49597

**Comment by lgritz** [comment]
Fix proposed in #684

**Comment by Nazg-Gul** [comment]
Checked it locally here just because.. Works fine, thanks for a quick fix :)

Any particular steps from our side to be done to move forward?

**Comment by lgritz** [comment]
I'm also merging this into RB-1.7.

It'll be in the next set of point releases I do at the end of the month. (It doesn't seem critical enough to make an off-schedule release just for that.)
