### ISSUE TITLE
Crash when compiling infinite for loop

### ISSUE THREAD

**Issue by roelandschoukens** [imageworks/OpenShadingLanguage#688]
A for loop without a condition statement will crash oslc:

```
for (;;)
{
    // stuff goes here
}
```

A possible fix is to ensure there's always a valid condition statement. An emtpy statement as above corresponds with a constant `true` value. For instance writing the `ASTloop_statement` as below fixes the crash.

```
ASTloop_statement::ASTloop_statement (OSLCompilerImpl *comp, LoopType looptype, ASTNode *init,
                    ASTNode *cond, ASTNode *iter, ASTNode *stmt)
    : ASTNode (loop_statement_node, comp, looptype, init, cond, iter, stmt)
{
    // replace empty condition with True value (in case it's left out in a for loop)
    if (!cond) { m_children[1] = new ASTliteral (comp, 1); }
}
```

**Comment by lgritz** [comment]
Sorry for the long delay, not sure how this escaped my notice.

You are quite right! Fix coming right up.
