### ISSUE TITLE
__nptl_deallocate_tsd() crash when closing an app with OSL loaded as a library on Linux

### ISSUE THREAD

**Issue by sfriedmapixar** [imageworks/OpenShadingLanguage#691]
This is pretty esoteric and may not be reasonably easy to fix for all uses, but I'm filing this so at least it's a known errata.

Due to [boost Ticket #3926](https://svn.boost.org/trac/boost/ticket/3926) and the use of boost::thread_specific_ptr to store thread-local data, when OSL is used as a shared library, you can run into occasional crashes in __nptl_deallocate_tsd(), which is the pthread thread local storage cleanup routine, when the application closes.

The sequence of events that leads to the problem is
1) load OSL as a shared library
2) start shading system and optimize a shader
3) this causes boost::thread_specific_ptr to register a pthread thread specific key and destructor pointing to code in the loaded library
4) clean up the shading system and unload the library
    --  at this point, the code for destructor that was registered with the pthread is unloaded because the LLVM_Util::PerThreadInfo are intentionally leaked, even having OSL clean up the shading system does not de-register the thread specific destructor.
5) closing the app causes the pthread library to do clean-up, calling the destructors for any per-thread
keys that are still registered.  Since the shared library is unloaded, this causes a segfault

We've worked around it by managing the thread specific data ourselves and passing it in for shading context PerThreadInfo, and adding the plumbing to get it all the way down into LLVM_Util::PerThreadInfo.  That may not be a good solution for users who don't manage their own thread local data.

**Comment by fpsunflower** [comment]
FWIW, in our renderer at SPI we also manually manage these contexts - we found it gave a measurable performance benefit over going through `boost::thread_specific_ptr`. Both `testshade` and `testrender` also work this way.

I  would be in favor of forcing manual management of these in the API to guide users towards the more efficient (and safer) solution by default.

**Comment by lgritz** [comment]
Is there still something here that reasonably should be fixed on the osl side?

**Comment by fpsunflower** [comment]
I would still be in favor of removing the automagic thread context creation since we've found in the past that `boost::thread_specific_ptr` is not particularly performant.

Since both `testshade` and `testrender` show how to do manual context creation, I don't think the automatic version is that critical.

**Comment by lgritz** [comment]
OK, in master I will deprecate it.
