### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by marsupial** [imageworks/OpenShadingLanguage#702]
Am I missing something or is c8e38df now causing the llvm::MemoryBuffer to be leaked?

**Comment by fpsunflower** [comment]
The code as it was didn't compile on our flavor of Linux (against LLVM 3.5). So it seemed most prudent to roll it back to what it was.

Are you sure about the ownership semantics here?

**Comment by marsupial** [comment]
The code you added seems to only be for LLVM-3.5. I have no idea who owns it on 3.5.

Everything above is returning a _unique_ptr_ from `getMemBuffer` and takes one as an argument to `getLazyBitcodeModule` (to avoid this issue I presume).

So if `getMemBuffer` returns a unique_ptr, which is then converted to a raw pointer, isn't it actually worse and returned _unique_ptr_ is actually a temporary therefore deleting after assignment?

**Comment by marsupial** [comment]
I guess the standards committee thought of this, it won't even compile anymore!
I'll submit a PR.

**Comment by marsupial** [comment]
#703

**Comment by lgritz** [comment]
Fixed by #703
