### ISSUE TITLE
OSLC performance problem when building shaders with large static arrays

### ISSUE THREAD

**Issue by luisbarrancos** [imageworks/OpenShadingLanguage#723]
When implementing a value noise function in OSL for [appleseed](https://github.com/appleseedhq) with the use of a large table (64k) of RNG numbers generated via drand48 and a known seed in order to match values with a DCC app, i noticed the resulting shader would take a considerable amount of time to compile, on average 26 seconds.
Three runs:
```
real	0m26.780s
user	0m26.686s
sys	0m0.051s
```
```
real	0m27.068s
user	0m26.918s
sys	0m0.060s
```
```
real	0m27.343s
user	0m27.189s
sys	0m0.052s
```
If using large static arrays would be unavoidable, what would be the best way to address this in OSL, and is this a known case?
There are other shaders involving the use of this RNG table and the cumulative effect is somewhat considerable.

The shader was built with OSL 1.7.6, LLVM 3.5 on Fedora 23. Zipfile attached.
[value_noise_test.zip](https://github.com/imageworks/OpenShadingLanguage/files/844670/value_noise_test.zip)

**Comment by fpsunflower** [comment]
The table is not used in `value_noise_2d` and removing it cuts the time roughly in half. This suggests the bottleneck is just in the parsing code somewhere.

I have a feeling there is just an `O(n^2)` type bug hiding somewhere, it should be possible to fix.

**Comment by fpsunflower** [comment]
Yup the whole thing is stuck on `ASTNode::append` which does a linear search to add each element to the end of the array. I'm sure there will be an easy way to reorganize this, Larry is more familiar with this code to suggest the proper fix though.

**Comment by dictoon** [comment]
> I have a feeling there is just an O(n^2) type bug hiding somewhere
Yup, that was my immediate suspicion when I saw the problem. Immediately reminded me of this blog: https://accidentallyquadratic.tumblr.com/
:)

**Comment by dictoon** [comment]
Hello! This is still an everyday annoyance for us: The time it takes to compile appleseed is _largely_ dominated by the time it takes to compile a handful of OSL shaders. Any chance for a fix?

**Comment by boberfly** [comment]
Hi all. Recently I tried building Appleseed's shaders against OSL 1.9.8 + LLVM 5.0.1 to match what Gaffer has defaulted to on Windows, and these shaders actually do generate but crash on exit which fails the build process. 

I can give you better details when I'm at home, but it was RelWithDebInfo not Debug as I couldn't build OSL in debug mode on Windows due to the internal shaders asserting when being built. Cheers!

**Comment by lgritz** [comment]
Sorry for the delay, I'll try to take a look at this.] issue.

**Comment by lgritz** [comment]
I'm happy to report that I have a good solution for this!  PR coming soon.

**Comment by lgritz** [comment]
For your example code (thanks!), it goes from compiling in ~26 seconds on my laptop, to compiling in 0.4 seconds.

**Comment by lgritz** [comment]
See #901 for proposed fix!
I will backport to release branches of OSL, but note that you will only see the speedup when you build with a new enough version of OIIO (for reasons that are explained in the PR, needed a new feature of the ref-counted pointers we use).

**Comment by dictoon** [comment]
Thanks Larry, very much appreciated!

**Comment by lgritz** [comment]
Merged the fix into master, I'm testing and will also backport to the release branch.
