### ISSUE TITLE
State of OSL

### ISSUE THREAD

**Issue by carsonbrownlee** [imageworks/OpenShadingLanguage#730]
hello,
I've been looking over OSL and it looks very promising, however I've run into a few issues.  I built OSL on Centos 7 off of branch RB-1.8 and about half of the tests fail, and only about half of the "testsuite/render-" tests produce a non black image using testrender.  To compile, I needed to remove a line for adding the  MCJIT llvm library in case that affected anything.  I'm using llvm 3.4.2.
Is this indicative of the state of OSL (or at least the testrender/testshader apps) or specific to my build/dependencies?  

Would blender be a better starting point for assessing the stability and functionality of OSL?
Is there a place that maintains a set of supported shaders comparable to something like the vMaterial Library, or would the best place for prebuilt shaders be an external package like blender if they can export to OSL?

**Comment by lgritz** [comment]
In what way do the tests fail, exactly? Crash? Incorrect result?

Which part of RB-1.8? The current head? A release tag?

Are you using llvm 3.4 because you're stuck with C++03? Or do you have the option to use a modern LLVM (beyond 3.4 does require C++11)?

**Comment by carsonbrownlee** [comment]
adding partial output below.  I'm assuming incorrect output, but haven't delved deeper.

I checked out RB-1.8 branch, latest commit was: 

I'm using llvm 3.4 simply because that's what Centos' package manager has and it was listed as supported.  I can update it manually if that may fix these issues.  

`
$ make test |& tee out.txt
make[1]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[2]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[  0%] Built target CopyFiles
[  2%] Built target testshade_dso
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[  5%] Built target oslnoise
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[  7%] Built target oslnoise_test
[ 15%] Built target oslquery
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[ 17%] Built target oslinfo
[ 28%] Built target oslcomp
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[ 30%] Built target oslc
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[ 37%] Built target shaders
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[ 83%] Built target oslexec
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Entering directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[ 85%] Built target llvmutil_test
make[3]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
[ 87%] Built target accum_test
[ 90%] Built target libtestshade
[ 94%] Built target testshade
[ 96%] Built target osl.imageio
[100%] Built target testrender
make[2]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
make[1]: Leaving directory `/home/carson/git/OpenShadingLanguage/build/linux64'
Running tests --force-new-ctest-process --output-on-failure...
Test project /home/carson/git/OpenShadingLanguage/build/linux64
        Start   1: and-or-not-synonyms
  1/306 Test   #1: and-or-not-synonyms ................   Passed    0.20 sec
        Start   2: and-or-not-synonyms.opt
  2/306 Test   #2: and-or-not-synonyms.opt ............   Passed    0.19 sec
        Start   3: aastep
  3/306 Test   #3: aastep .............................***Failed    0.17 sec
sh: bin/idiff: No such file or directory
sh: bin/idiff: No such file or directory
test source dir = ../../../../testsuite/aastep
command = ../../src/oslc/oslc test.osl >> out.txt 2>&1 ;
../../src/testshade/testshade -g 64 64 -od uint8 -o Cout out.tif test >> out.txt 2>&1 ;

PASS: out.txt matches ref/out.txt
NO MATCH for out.tif
FAIL out.tif

        Start   4: aastep.opt
  4/306 Test   #4: aastep.opt .........................***Failed    0.22 sec
sh: bin/idiff: No such file or directory
sh: bin/idiff: No such file or directory
test source dir = ../../../../testsuite/aastep
command = ../../src/oslc/oslc test.osl >> out.txt 2>&1 ;
../../src/testshade/testshade -g 64 64 -od uint8 -o Cout out.tif test >> out.txt 2>&1 ;

PASS: out.txt matches ref/out.txt
NO MATCH for out.tif
FAIL out.tif

        Start   5: arithmetic
  5/306 Test   #5: arithmetic .........................   Passed    0.19 sec
        Start   6: arithmetic.opt
  6/306 Test   #6: arithmetic.opt .....................   Passed    0.21 sec
        Start   7: array
  7/306 Test   #7: array ..............................   Passed    0.22 sec
        Start   8: array.opt
  8/306 Test   #8: array.opt ..........................   Passed    0.20 sec
        Start   9: array-derivs
  9/306 Test   #9: array-derivs .......................   Passed    0.20 sec
        Start  10: array-derivs.opt
 10/306 Test  #10: array-derivs.opt ...................   Passed    0.17 sec
        Start  11: array-range
 11/306 Test  #11: array-range ........................   Passed    0.13 sec
        Start  12: array-range.opt
 12/306 Test  #12: array-range.opt ....................   Passed    0.16 sec
        Start  13: blackbody
 13/306 Test  #13: blackbody ..........................***Failed    0.22 sec
sh: bin/idiff: No such file or directory
sh: bin/idiff: No such file or directory
test source dir = ../../../../testsuite/blackbody
command = ../../src/oslc/oslc test.osl >> out.txt 2>&1 ;
../../src/testshade/testshade -g 1000 64 -od half -o Cout out.exr test >> out.txt 2>&1 ;

PASS: out.txt matches ref/out.txt
NO MATCH for out.exr
FAIL out.exr

        Start  14: blackbody.opt
 14/306 Test  #14: blackbody.opt ......................***Failed    0.21 sec
sh: bin/idiff: No such file or directory
sh: bin/idiff: No such file or directory
test source dir = ../../../../testsuite/blackbody
command = ../../src/oslc/oslc test.osl >> out.txt 2>&1 ;
../../src/testshade/testshade -g 1000 64 -od half -o Cout out.exr test >> out.txt 2>&1 ;

PASS: out.txt matches ref/out.txt
NO MATCH for out.exr
FAIL out.exr


...

300/306 Test #300: wavelength_color ...................***Failed    0.24 sec
sh: bin/idiff: No such file or directory
sh: bin/idiff: No such file or directory
test source dir = ../../../../testsuite/wavelength_color
command = ../../src/oslc/oslc test.osl >> out.txt 2>&1 ;
../../src/testshade/testshade -g 1000 64 -od float -o Cout out.exr test >> out.txt 2>&1 ;

PASS: out.txt matches ref/out.txt
NO MATCH for out.exr
FAIL out.exr

        Start 301: wavelength_color.opt
301/306 Test #301: wavelength_color.opt ...............***Failed    0.24 sec
sh: bin/idiff: No such file or directory
sh: bin/idiff: No such file or directory
test source dir = ../../../../testsuite/wavelength_color
command = ../../src/oslc/oslc test.osl >> out.txt 2>&1 ;
../../src/testshade/testshade -g 1000 64 -od float -o Cout out.exr test >> out.txt 2>&1 ;

PASS: out.txt matches ref/out.txt
NO MATCH for out.exr
FAIL out.exr

        Start 302: xml
302/306 Test #302: xml ................................   Passed    0.20 sec
        Start 303: xml.opt
303/306 Test #303: xml.opt ............................   Passed    0.19 sec
        Start 304: unit_accum
304/306 Test #304: unit_accum .........................   Passed    0.05 sec
        Start 305: unit_llvmutil
305/306 Test #305: unit_llvmutil ......................   Passed    0.03 sec
        Start 306: unit_oslnoise
306/306 Test #306: unit_oslnoise ......................   Passed    5.52 sec

67% tests passed, 102 tests failed out of 306

Total Test time (real) =  78.61 sec

The following tests FAILED:
	  3 - aastep (Failed)
	  4 - aastep.opt (Failed)
	 13 - blackbody (Failed)
	 14 - blackbody.opt (Failed)
	 19 - bug-array-heapoffsets (Failed)
	 20 - bug-array-heapoffsets.opt (Failed)
	 23 - bug-outputinit (Failed)
	 24 - bug-outputinit.opt (Failed)
	 29 - cellnoise (Failed)
	 30 - cellnoise.opt (Failed)
	 39 - compile-buffer (Failed)
	 40 - compile-buffer.opt (Failed)
	 55 - draw_string (Failed)
	 56 - draw_string.opt (Failed)
	 74 - getsymbol-nonheap (Failed)
	 75 - getsymbol-nonheap.opt (Failed)
	 76 - gettextureinfo (Failed)
	 77 - gettextureinfo.opt (Failed)
	 78 - group-outputs (Failed)
	 79 - group-outputs.opt (Failed)
	108 - layers-repeatedoutputs (Failed)
	109 - layers-repeatedoutputs.opt (Failed)
	110 - linearstep (Failed)
	111 - linearstep.opt (Failed)
	130 - noise (Failed)
	131 - noise.opt (Failed)
	132 - noise-cell (Failed)
	133 - noise-cell.opt (Failed)
	134 - noise-gabor (Failed)
	135 - noise-gabor.opt (Failed)
	136 - noise-gabor2d-filter (Failed)
	137 - noise-gabor2d-filter.opt (Failed)
	138 - noise-gabor3d-filter (Failed)
	139 - noise-gabor3d-filter.opt (Failed)
	140 - noise-perlin (Failed)
	141 - noise-perlin.opt (Failed)
	142 - noise-uperlin (Failed)
	143 - noise-uperlin.opt (Failed)
	144 - noise-simplex (Failed)
	145 - noise-simplex.opt (Failed)
	146 - noise-usimplex (Failed)
	147 - noise-usimplex.opt (Failed)
	148 - pnoise (Failed)
	149 - pnoise.opt (Failed)
	150 - pnoise-cell (Failed)
	151 - pnoise-cell.opt (Failed)
	152 - pnoise-gabor (Failed)
	153 - pnoise-gabor.opt (Failed)
	154 - pnoise-perlin (Failed)
	155 - pnoise-perlin.opt (Failed)
	156 - pnoise-uperlin (Failed)
	157 - pnoise-uperlin.opt (Failed)
	190 - osl-imageio (Failed)
	191 - osl-imageio.opt (Failed)
	198 - reparam (Failed)
	199 - reparam.opt (Failed)
	200 - render-background.opt (Failed)
	201 - render-bumptest.opt (Failed)
	202 - render-cornell.opt (Failed)
	203 - render-furnace-diffuse.opt (Failed)
	204 - render-microfacet.opt (Failed)
	205 - render-oren-nayar.opt (Failed)
	206 - render-veachmis.opt (Failed)
	207 - render-ward.opt (Failed)
	212 - spline (Failed)
	213 - spline.opt (Failed)
	216 - spline-derivbug (Failed)
	217 - spline-derivbug.opt (Failed)
	244 - testshade-expr (Failed)
	245 - testshade-expr.opt (Failed)
	246 - texture-alpha (Failed)
	247 - texture-alpha.opt (Failed)
	248 - texture-blur (Failed)
	249 - texture-blur.opt (Failed)
	250 - texture-connected-options (Failed)
	251 - texture-connected-options.opt (Failed)
	252 - texture-derivs (Failed)
	253 - texture-derivs.opt (Failed)
	254 - texture-errormsg (Failed)
	255 - texture-errormsg.opt (Failed)
	256 - texture-firstchannel (Failed)
	257 - texture-firstchannel.opt (Failed)
	258 - texture-interp (Failed)
	259 - texture-interp.opt (Failed)
	260 - texture-missingcolor (Failed)
	261 - texture-missingcolor.opt (Failed)
	262 - texture-simple (Failed)
	263 - texture-simple.opt (Failed)
	264 - texture-smallderivs (Failed)
	265 - texture-smallderivs.opt (Failed)
	266 - texture-swirl (Failed)
	267 - texture-swirl.opt (Failed)
	268 - texture-udim (Failed)
	269 - texture-udim.opt (Failed)
	270 - texture-width (Failed)
	271 - texture-width.opt (Failed)
	272 - texture-withderivs (Failed)
	273 - texture-withderivs.opt (Failed)
	274 - texture-wrap (Failed)
	275 - texture-wrap.opt (Failed)
	300 - wavelength_color (Failed)
	301 - wavelength_color.opt (Failed)
Errors while running CTest
make: *** [test] Error 8


`

**Comment by lgritz** [comment]
> sh: bin/idiff: No such file or directory

It's trying to use the OpenImageIO `idiff` utility to compare test images to reference images, and not finding it. The way the error message is worded, it looks like you have an $OPENIMAGEIOHOME env variable present, but it is empty, so you're getting "bin/idiff". If the variable doesn't exist at all, it will just look for "idiff" and hope it's in your path.

If idiff is not in your $PATH, then please set environment variable $OPENIMAGEIOHOME to the prefix where your OIIO installation is.

**Comment by carsonbrownlee** [comment]
odd, env | grep OPENIMAGE returns nothing, and setting it to /user/local appeared to have no affect.  Perhaps python is grabbing another set of env vars?  At any rate, I modified the code to not append bin to the path and it got rid of that error.  A few tests still fail, listed below.  Any idea why some of the render- tests are showing up black?


`
test source dir = ../../../../testsuite/compile-buffer
command = ../../src/testshade/testshade --inbuffer test >> out.txt 2>&1 ;

#### Error: this command failed:  ../../src/testshade/testshade --inbuffer test >> out.txt 2>&1 
FAIL

        Start  40: compile-buffer.opt
 40/306 Test  #40: compile-buffer.opt .................***Failed    0.11 sec
test source dir = ../../../../testsuite/compile-buffer
command = ../../src/testshade/testshade --inbuffer test >> out.txt 2>&1 ;

#### Error: this command failed:  ../../src/testshade/testshade --inbuffer test >> out.txt 2>&1 
FAIL

        Start  41: component-range


...

190/306 Test #190: osl-imageio ........................***Failed    0.17 sec
test source dir = ../../../../testsuite/osl-imageio
command = ../../src/oslc/oslc ramp.osl >> out.txt 2>&1 ;
oiiotool "ramp.oso?RES=64" -d uint8 -o ramp-oso-default.tif >> out.txt 2>&1 ;
oiiotool "ramp.oso?RES=64&color topright=0,0,1" -d uint8 -o ramp-oso-blue.tif >> out.txt 2>&1 ;
oiiotool "ramp.oso?RES=64&color bottomright=0,1,1&TILE=32x32" -d uint8 -o ramp-oso-tiles.tif >> out.txt 2>&1 ;
oiiotool "result=sin(40*s)/2+0.5.oslbody?RES=256x256&MIP=1" -selectmip 2 -d uint8 -o wave-mip.tif >> out.txt 2>&1 ;

#### Error: this command failed:  
oiiotool "ramp.oso?RES=64" -d uint8 -o ramp-oso-default.tif >> out.txt 2>&1 
FAIL

        Start 191: osl-imageio.opt
191/306 Test #191: osl-imageio.opt ....................***Failed    0.19 sec
test source dir = ../../../../testsuite/osl-imageio
command = ../../src/oslc/oslc ramp.osl >> out.txt 2>&1 ;
oiiotool "ramp.oso?RES=64" -d uint8 -o ramp-oso-default.tif >> out.txt 2>&1 ;
oiiotool "ramp.oso?RES=64&color topright=0,0,1" -d uint8 -o ramp-oso-blue.tif >> out.txt 2>&1 ;
oiiotool "ramp.oso?RES=64&color bottomright=0,1,1&TILE=32x32" -d uint8 -o ramp-oso-tiles.tif >> out.txt 2>&1 ;
oiiotool "result=sin(40*s)/2+0.5.oslbody?RES=256x256&MIP=1" -selectmip 2 -d uint8 -o wave-mip.tif >> out.txt 2>&1 ;

#### Error: this command failed:  
oiiotool "ramp.oso?RES=64" -d uint8 -o ramp-oso-default.tif >> out.txt 2>&1 
FAIL


...

202/306 Test #202: render-cornell.opt .................***Failed    0.69 sec
Comparing "out.exr" and "ref/out.exr"
256 x 256, 3 channel
  Mean error = 0.0463048
  RMS error = 0.0609431
  Peak SNR = 50.6157
  Max error  = 0.306152 @ (215, 87, B)
  61346 pixels (93.6%) over 0.01
  64746 pixels (98.8%) over 0.005
FAILURE
Comparing "out.exr" and "ref/out.exr"
256 x 256, 3 channel
  Mean error = 0.0463048
  RMS error = 0.0609431
  Peak SNR = 50.6157
  Max error  = 0.306152 @ (215, 87, B)
  61346 pixels (93.6%) over 0.01
  64746 pixels (98.8%) over 0.005
FAILURE
test source dir = ../../../../testsuite/render-cornell
command = ../../src/oslc/oslc emitter.osl >> out.txt 2>&1 ;
../../src/oslc/oslc matte.osl >> out.txt 2>&1 ;
../../src/oslc/oslc metal.osl >> out.txt 2>&1 ;
../../src/testrender/testrender  -v --stats -r 256 256 -aa 4 cornell.xml out.exr >> out.txt 2>&1 ;

NO MATCH for out.exr
FAIL out.exr

        Start 203: render-furnace-diffuse.opt

...

205/306 Test #205: render-oren-nayar.opt ..............***Failed    0.54 sec
Comparing "out.exr" and "ref/out.exr"
320 x 240, 3 channel
  Mean error = 0.0757942
  RMS error = 0.110048
  Peak SNR = 19.1683
  Max error  = 0.59668 @ (10, 123, R)
  42732 pixels (55.6%) over 0.06
  53154 pixels (69.2%) over 0.03
FAILURE
Comparing "out.exr" and "ref/out.exr"
320 x 240, 3 channel
  Mean error = 0.0757942
  RMS error = 0.110048
  Peak SNR = 19.1683
  Max error  = 0.59668 @ (10, 123, R)
  42732 pixels (55.6%) over 0.06
  53154 pixels (69.2%) over 0.03
FAILURE
test source dir = ../../../../testsuite/render-oren-nayar
command = ../../src/oslc/oslc checkerboard.osl >> out.txt 2>&1 ;
../../src/oslc/oslc emitter.osl >> out.txt 2>&1 ;
../../src/oslc/oslc matte.osl >> out.txt 2>&1 ;
../../src/oslc/oslc rough_matte.osl >> out.txt 2>&1 ;
../../src/testrender/testrender  -v --stats -r 320 240 -aa 4 scene.xml out.exr >> out.txt 2>&1 ;

NO MATCH for out.exr
FAIL out.exr

        Start 206: render-veachmis.opt
206/306 Test #206: render-veachmis.opt ................***Failed    0.70 sec
Comparing "out.exr" and "ref/out.exr"
320 x 240, 3 channel
  Mean error = 0.0183451
  RMS error = 0.202123
  Peak SNR = 47.7633
  Max error  = 39.2734 @ (69, 69, B)
  34302 pixels (44.7%) over 0.008
  44774 pixels (58.3%) over 0.004
FAILURE
Comparing "out.exr" and "ref/out.exr"
320 x 240, 3 channel
  Mean error = 0.0183451
  RMS error = 0.202123
  Peak SNR = 47.7633
  Max error  = 39.2734 @ (69, 69, B)
  34302 pixels (44.7%) over 0.008
  44774 pixels (58.3%) over 0.004
FAILURE
test source dir = ../../../../testsuite/render-veachmis
command = ../../src/oslc/oslc checkerboard.osl >> out.txt 2>&1 ;
../../src/oslc/oslc emitter.osl >> out.txt 2>&1 ;
../../src/oslc/oslc matte.osl >> out.txt 2>&1 ;
../../src/oslc/oslc phong.osl >> out.txt 2>&1 ;
../../src/testrender/testrender  -v --stats -r 320 240 -aa 4 veach.xml out.exr >> out.txt 2>&1 ;

NO MATCH for out.exr
FAIL out.exr

        Start 207: render-ward.opt

...

244/306 Test #244: testshade-expr .....................***Failed    0.19 sec
Comparing "out.tif" and "ref/out.tif"
PASS
test source dir = ../../../../testsuite/testshade-expr
command = ../../src/testshade/testshade -v -g 64 64 -od uint8 -o result out.tif -expr 'result=color(u,v,0)' >> out.txt 2>&1 ;

NO MATCH for out.txt
FAIL out.txt
-----out.txt----->
ERROR: <buffer>:0: warning: Unable to find "stdosl.h"
Expression-based shader text is:
---
shader expr_0 (
    float s = u [[ int lockgeom=0 ]],
    float t = v [[ int lockgeom=0 ]],
    output color result = 0,
    output float alpha = 1,
  )
{
    result=color(u,v,0)
    ;
}
---
Shader group:
---
shader expr_0  ;

---

Shader group "" layers are:
    


Output result to out.tif
<----------
Diff was:
-------
--- out.txt	Thu Apr  6 17:18:01 2017
+++ ref/out.txt	Wed Apr  5 13:27:15 2017
@@ -1,4 +1,3 @@
-ERROR: <buffer>:0: warning: Unable to find "stdosl.h"
 Expression-based shader text is:
 ---
 shader expr_0 (

PASS: out.tif matches ref/out.tif

        Start 245: testshade-expr.opt
245/306 Test #245: testshade-expr.opt .................***Failed    0.14 sec
Comparing "out.tif" and "ref/out.tif"
PASS
test source dir = ../../../../testsuite/testshade-expr
command = ../../src/testshade/testshade -v -g 64 64 -od uint8 -o result out.tif -expr 'result=color(u,v,0)' >> out.txt 2>&1 ;

NO MATCH for out.txt
FAIL out.txt
-----out.txt----->
ERROR: <buffer>:0: warning: Unable to find "stdosl.h"
Expression-based shader text is:
---
shader expr_0 (
    float s = u [[ int lockgeom=0 ]],
    float t = v [[ int lockgeom=0 ]],
    output color result = 0,
    output float alpha = 1,
  )
{
    result=color(u,v,0)
    ;
}
---
Shader group:
---
shader expr_0  ;

---

Shader group "" layers are:
    


Output result to out.tif
<----------
Diff was:
-------
--- out.txt	Thu Apr  6 17:18:01 2017
+++ ref/out.txt	Wed Apr  5 13:27:15 2017
@@ -1,4 +1,3 @@
-ERROR: <buffer>:0: warning: Unable to find "stdosl.h"
 Expression-based shader text is:
 ---
 shader expr_0 (

PASS: out.tif matches ref/out.tif

        Start 246: texture-alpha

...

97% tests passed, 10 tests failed out of 306

Total Test time (real) =  91.63 sec

The following tests FAILED:
	 39 - compile-buffer (Failed)
	 40 - compile-buffer.opt (Failed)
	190 - osl-imageio (Failed)
	191 - osl-imageio.opt (Failed)
	202 - render-cornell.opt (Failed)
	205 - render-oren-nayar.opt (Failed)
	206 - render-veachmis.opt (Failed)
	207 - render-ward.opt (Failed)
	244 - testshade-expr (Failed)
	245 - testshade-expr.opt (Failed)
Errors while running CTest
make: *** [test] Error 8


`

**Comment by lgritz** [comment]
set OSLHOME to the dist area

The tests are just for me and for CI, we don't expect users to run them.
I should probably take a pass at it and make sure it's more robust if you don't have all the magic environment variables set up, be sure it looks in obvious default places.

In any case, this is nothing to worry about.

**Comment by lgritz** [comment]
#737 will make the build and test work fine without OSLHOME being set.
Closing.
