### ISSUE TITLE
Outdated docs covering array of structures, with array as element?

### ISSUE THREAD

**Issue by luisbarrancos** [imageworks/OpenShadingLanguage#734]
In the documentation, the section covering structures lists as an example a structure with an float array as element, and an array of such structures, but OSLC fails when building the following snippet:
```
struct X
{
    float foo;
    float bar[2];
};

surface test()
{
    X x[4];

    for (int i = 0; i < 4; ++i)
    {
        x[i].bar[0] = i;
        x[i].bar[1] = i + 23;
    }
    Ci = x[1].bar[0];
}  
```
with the following message
foo.osl:9: error: Nested structs with >1 levels of arrays are not allowed: X

Is this supposed to be supported, or the docs weren't updated to reflect subsequent changes?

**Comment by lgritz** [comment]
Sorry, I think the docs are out of sync with the current limitation of not allowing nested arrays within structs.

**Comment by lgritz** [comment]
I will fix this in the docs.
