### ISSUE TITLE
Building with MSVC 2013, unresolved external symbols from OIIO as shared

### ISSUE THREAD

**Issue by boberfly** [imageworks/OpenShadingLanguage#748]
### Problem

Trying to compile OSL Release 1.7.5 as per the version which Gaffer packages, but on Windows. I've stumbled upon a linking error here when linking to OpenImageIO as a DLL:

https://gist.github.com/boberfly/154f01ce8cee913b4fa28990e20597ec

I haven't tried master yet, I wanted to keep conservative with versions so that it links with LLVM 3.4. My proposed fix was to make sure OpenImageIO_Util.lib was a part of the target link libraries of each lib/bin of OSL but this seemed to have no effect. Linking with a static version of OIIO works.

### Steps to Reproduce

1. Build all the dependencies, OIIO as a dynamic lib.
2. Build OSL, static or dynamic.
3. Linker error.

### Versions

* OSL branch/version: 1.7.5 Release from gafferDependencies custom branch of mine:
https://github.com/boberfly/gafferDependencies/tree/windows
* OS: 
Windows 10 64-bit
* C++ compiler: 
MSVC 2013 64-bit
* LLVM version: 
3.4 (static)
* OIIO version: 
Both 1.6.14 and 1.7.13 (dynamic)

Cheers

**Comment by boberfly** [comment]
For future reference I must've missed this CMake flag, which is on by default:
`-DUSE_OIIO_STATIC=OFF`
Cheers...

**Comment by lgritz** [comment]
Interestingly, in the master branch, this variable is totally disabled. 
Considering that the usual practice is to use dynamic libs (right?), I wonder now why this would default to ON. Should that be changed?

**Comment by boberfly** [comment]
@lgritz possibly, I guess it depends on the usual practice yeah, for my Gaffer windows porting efforts I've tried to keep things as dynamically-linked as possible, although some things just don't build right otherwise like LLVM but I think this is an ok exception as OSL is the only library using it directly so far. 

Maybe for platforms which don't do dynamic libs freely in runtimes, like perhaps iOS it might affect? Most likely these libs are for tools anyway and link to bigger VFX tools so probably best to default to dynamic. ;)
