### ISSUE TITLE
Contradiction in documentation for matrix("space", float)

### ISSUE THREAD

**Issue by roelandschoukens** [imageworks/OpenShadingLanguage#770]
The call `matrix("object", 1.0)` is documented in two places.

Let's assume object space is defined as a translation of the origin to the point `(10, 0, 0)`, and that the common space is world space. So the point `(0, 0, 0)` in object space corresponds to the point `(10, 0, 0)` in common space.

There are two sections documenting this call, and they are contradicting each other:

**§5.5 Matrix**

>     // Construct matrices relative to something other than "common"
>     matrix q = matrix ("shader", 1);
>
> The first form creates the matrix that transforms points from **"common" space to "shader"
> space**. Transforming points by this matrix is identical to calling `transform("shader",...)`.

That implies `matrix("object", 1)` returns the common-to-object space matrix. This is the inverse of the object transform matrix, i.e. a translation by `(-10, 0, 0)`.

**§7.4 Matrix functions**

> `matrix matrix (string fromspace, float f)`
> 
> Constructs a matrix relative to the named space, multiplying it by the space-to-common
> transformation matrix. If the coordinate system name is unknown, it will be assumed to
> be the identity matrix.
>
> Note that `matrix (space, 1)` returns the **space-to-common** transformation matrix. If
> the coordinate system name is unknown, it will be assumed to be the identity matrix.

Which implies the returned matrix will be the object transform matrix, i.e. a translation of `(+10, 0, 0)`.

One of these sections is wrong and should be fixed.

**Comment by lgritz** [comment]
This was fixed a while back, thanks for the report.
