### ISSUE TITLE
while statement doesn't work correctly

### ISSUE THREAD

**Issue by kazkit** [imageworks/OpenShadingLanguage#776]
### Problem

**Expected behavior:** 
"while" statement should support a conditional that includes only a variable.
Now "if " statement in OSL works.
**Actual behavior:**  
while statement doesn't work if I used C-style conditional.

### Steps to Reproduce

1. if I used only a variable as conditional,while statement didn't work correctly.
```
int hit=1;
while(hit){
    hit = 0;
}
```
2. To work it,I had to specify conditional using a comparison operator explicitly.
```
int hit=1;
while(hit==1){
   	hit = 0;
}
```

**Comment by louis-coffelt** [comment]
OSL is an infringement of my copyrighted work. US copyright registration No. TxU2035517
[CopyrightCoffelt_.pdf](https://github.com/imageworks/OpenShadingLanguage/files/1183977/CopyrightCoffelt_.pdf)

**Comment by lgritz** [comment]
Sorry for this falling through the cracks, but oh dear, you are right. How did we not discover this?

Fix coming.
