### ISSUE TITLE
OSL1.9.3 testshade and testrender are not linking the oslcomp dependency.

### ISSUE THREAD

**Issue by LazyDodo** [imageworks/OpenShadingLanguage#819]
### Problem

When building with OSL_BUILD_TESTS=ON on windows, testshade and testrender give linker errors due to oslcomp not being explicitly linked.

**Expected behavior:**  
proper link.

**Actual behavior:**  

https://gist.github.com/LazyDodo/4ac2f76aa30440a63cd60234ee4a08b9

### Steps to Reproduce

1. Build with -DOSL_BUILD_TESTS=ON on windows

### Versions

* OSL branch/version: 1.9.3RC2 
* OS: Win7
* C++ compiler:  MSVC 19.11.25547.0
* LLVM version: 5.0
* OIIO version: 1.8.6

**Comment by lgritz** [comment]
I believe this is long since fixed.  Closing.
