### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by davidgiven** [imageworks/OpenShadingLanguage#848]
It's 0520 and I'm at an airport, so this may not make _complete_ sense, but...

I've been experimenting with building OSL on ARM Linux. The good news is that it seems to very nearly work. Simply adding `armv4l` to the list of supported architectures in `src/make/detectplatform.mk` is all the needs to be done, and then it builds out of the box and the tests run.

A very few of the tests fail --- I include a log of a test run. 

[testlog.txt](https://github.com/imageworks/OpenShadingLanguage/files/1666603/testlog.txt)

```
        102 - isconnected (Failed)
        103 - isconnected.opt (Failed)
        236 - string (Failed)
        237 - string.opt (Failed)
        290 - texture-udim (Failed)
        291 - texture-udim.opt (Failed)
```

`string` is failing because string hashes are different; the OpenImageIO hash function isn't defined to be the same from platform to platform. `isconnected` looks like an 1e-329 number is coming out as 0 on the ARM --- a floating point accuracy issue? That seems weird to me as it should all be IEEE float. `texture` is failing because oiiotool can't find the default font (which is apparently not well defined).

The only one of these which looks at all interesting is `isconnected`. Other than that, it just needs the tests fixing and it should be good to go...

**Comment by lgritz** [comment]
That's actually much better than I expected (for a platform we haven't tried building at all)!

The string test is failing only on use of the hash (the last few lines of testsuite/string/test.osl)?

**Comment by davidgiven** [comment]
Looks like it --- the test log should contain the actual diffs. (The test suite is pretty nice.) I'm reasonably sure that's WAI from looking at the comments in OpenImageIO's farmhash.

Could the isconnected issue be precision loss between the ARM's 64-bit floats and the x87's 80-bit? Does SSE even _have_ 80 bit these days?

Note that this is only with LLVM 5.0; I haven't tried with older versions. I know that the LLVM ARM JIT has had a lot of work recently.

**Comment by lgritz** [comment]
SSE is 32 & 64 bit IEEE. The 80 bit x87 is long gone. 

That value isn't from "math", it should just be copied, I would think. A precision problem should be on the order of 1e-6 x the values involved. No, `4.94066e-324` smells more like uninitialized memory to me, some copy that didn't happen, something like that.

**Comment by davidgiven** [comment]
You can tell how long it's been since I've touched i386 floating point code.

I note that 4.94066e-324 is stored in memory as 0x0000000000000001, which smells a bit like a parameter passing issue. But if that were broken I'd expect that more tests would fail.

**Comment by lgritz** [comment]
Oh my, that is a suspicious value!

**Comment by lgritz** [comment]
Closing, since this discussion seems to have died off. If somebody is still working on an ARM port and still experiencing problems, I welcome re-filing issues or taking discussion to osl-dev mail list. I'm happy to help with advice, but I certainly don't have any way to build or test on ARM myself.
