### ISSUE TITLE
gcc vs clang testrender failures

### ISSUE THREAD

**Issue by BruceCherniak** [imageworks/OpenShadingLanguage#851]
OSL (master head and RB-1.9) compiled with gcc fails several more tests than when compiled with clang.

### Problem
OSL built with gcc fails the following testrender scenes, whereas clang passes:
render-cornell
render-oren-nayar
render-veachmis
render-ward

Simply using the clang generated "testrender" executable in the gcc build tree is sufficient for the tests to run correctly.

**Expected behavior:** gcc and clang should produce the same test results.

**Actual behavior:** gcc produced "testrender" executable has several suspect failures.  Images produced by the gcc executable are far too dark.

### Steps to Reproduce
(gcc is the default compiler)
1. make; make test   [this produces 8 failures]
2. export MYCC=clang MYCXX=clang++
3. make nuke; make; make test   [this produces 4 failures]
4. save build/linux64/src/testrender/testrender
5. unset MYCC MYCXX
6. make nuke; make; make test   [produces original 8 failures]
7. replace build/linux64/src/testrender/testrender with saved version
8. make test   [the 4 render-* failures now pass]

### Versions

* OSL branch/version:  master and RB-1.9
* OS: ubuntu 17.10 and manjaro archlinux
* C++ compiler:  gcc 7.2 and clang 5.0
* LLVM version:  5.0
* OIIO version:  master

**Comment by fpsunflower** [comment]
Have you tried opt vs. debug in both compilers? It would help discount an optimizer related issue.

**Comment by BruceCherniak** [comment]
No change.  Debug build; clang still passes, gcc fails.

To further limit differences, I added USE_BOOST_WAVE=1 to the clang build so that both use the same preprocessor.  No change.

**Comment by marsupial** [comment]
I'm seeing the same tests fail with VisualStudio-2017.
They do pass with VisualStudio-2015.

**Comment by lgritz** [comment]
I've had a very hard time making these render tests produce pixel-identical images on all compiler versions and platforms. I still don't understand why. But I'm very certain that it's because of testrender sampling internals, and not with OSL itself. I can't justify spending more time tracking it down, and this is is of no real consequence, so we can just increase the comparison tolerance or skip those few tests on CI tests if necessary. Closing.

**Comment by lgritz** [comment]
PS. If somebody really wants to track this down, I would welcome a PR to fix testrender so it absolutely guarantees identical output pixels on all platforms and compilers.
