### ISSUE TITLE
Small typography mistake p. 57 in the pdf.

### ISSUE THREAD

**Issue by Ti-R** [imageworks/OpenShadingLanguage#870]
Hello,
I found a small typography mistake p. 57 in the pdf.

### Problem

**Expected behavior:**  
`int hash (int i)`

**Actual behavior:**  
`int hash) (int i)`

### Steps to Reproduce

Inside the last documentation p. 57, the problem appear on the page.
https://github.com/imageworks/OpenShadingLanguage/blob/master/src/doc/osl-languagespec.pdf

### Versions

Master and 1.9.7

**Comment by lgritz** [comment]
Thanks for the alert, fixing.

**Comment by lgritz** [comment]
Thanks for the alert, fixing.
