### ISSUE TITLE
ShadingSystem::getattribute closures_needed ignores nested closures.

### ISSUE THREAD

**Issue by est77** [imageworks/OpenShadingLanguage#884]
When using closures that take other closures as argumens, for example to do layering:

Ci = as_coat(diffuse(N));

Querying the number and type of closures needed ignores the nested closures:

shading_system->getattribute("num_closures_needed") == 1;
shading_system->getattribute("closures_needed") == {"as_coat"};

Would it be possible to include the nested closures in the results of the getattribute calls?

**Comment by fpsunflower** [comment]
This seems like a bug, from what I read of the code - I think it should catch both in this case. It just scans through the list of post-optimized ops to figure out which closures might be created.

Do you see the `unknown_closures_needed` become `true` by any chance?

**Comment by est77** [comment]
I wrote a quick test using the OSL version we are currently using and I could not reproduce it.
Maybe I did something wrong when I tried this before or maybe it has been fixed in an OSL update.

Seems to work correctly, so I am closing the issue.

Thanks!

**Comment by lgritz** [comment]
It seems that procrastination has paid off for me once again!

I suspect that this was fixed as a side effect of some other patch at some point.
