### ISSUE TITLE
osltoy (master) failing to build with link errors with msvc14

### ISSUE THREAD

**Issue by exavi** [imageworks/OpenShadingLanguage#895]
### Problem

osltoy seems to not build correctly with MSVC14.

**Expected behavior:** 

Full build of osl, including osltoy.

**Actual behavior:**  

If I don't specify the Qt5 location, osltoy won't try to build, and everything works as excpected, I get usable libraries, however, when building with osltoy, it fails to build with the following error: 
(I can send a gist of the whole log, but this is the only error)

`osltoyapp.obj : error LNK2019: unresolved external symbol "public: __cdecl OSL_v1_10::OSLQuery::Parameter::Parameter(struct OSL_v1_10::OSLQuery::Parameter const &)" (??0Parameter@OSLQuery@OSL_v1_10@@QEAA@AEBU012@@Z) referenced in function "class std::shared_ptr<class OSL_v1_10::ParamRec> __cdecl std::make_shared<class OSL_v1_10::ParamRec,struct OSL_v1_10::OSLQuery::Parameter const &>(struct OSL_v1_10::OSLQuery::Parameter const &)" (??$make_shared@VParamRec@OSL_v1_10@@AEBUParameter@OSLQuery@2@@std@@YA?AV?$shared_ptr@VParamRec@OSL_v1_10@@@0@AEBUParameter@OSLQuery@OSL_v1_10@@@Z) [C:\libs\__sources\OpenShadingLanguage-master\OpenShadingLanguage-master\build_rel\src\osltoy\osltoy.vcxproj]  C:\libs\__sources\OpenShadingLanguage-master\OpenShadingLanguage-master\build_rel\src\osltoy\Release\osltoy.exe : fatal error LNK1120: 1 unresolved externals [C:\libs\__sources\OpenShadingLanguage-master\OpenShadingLanguage-master\build_rel\src\osltoy\osltoy.vcxproj]`

### Steps to Reproduce

I ran cmake directly, rather than make, not sure if this would make any difference, but it's worth mentioning, here is the command I'm running it with, not very useful but shows the versions I'm using for everything:

```
cmake -G "Visual Studio 14 Win64" -DCMAKE_INSTALL_PREFIX=C:/libs/OpenShadingLanguage-master-vs2015_x64_rel -DBOOST_ROOT=C:/libs/boost-1.61.0-vs2015_x64 -DBOOST_LIBRARYDIR=C:/libs/boost-1.61.0-vs2015_x64/lib64-msvc-14.0 -DZLIB_INCLUDE_DIR=C:/libs/zlib-1.2.8-vs2015_x64_rel/include -DZLIB_LIBRARY=C:/libs/zlib-1.2.8-vs2015_x64_rel/lib/zlib.lib -DILMBASE_INCLUDE_PATH=C:/libs/OpenEXR-2.2.0-vs2015_x64_rel/include -DOPENEXR_INCLUDE_PATH=C:/libs/OpenEXR-2.2.0-vs2015_x64_rel/include -DOPENEXR_IMATH_LIBRARY=C:/libs/OpenEXR-2.2.0-vs2015_x64_rel/lib/Imath-2_2.lib -DOPENEXR_ILMIMF_LIBRARY=C:/libs/OpenEXR-2.2.0-vs2015_x64_rel/lib/IlmImf-2_2.lib -DOPENEXR_IEX_LIBRARY=C:/libs/OpenEXR-2.2.0-vs2015_x64_rel/lib/Iex-2_2.lib -DOPENEXR_HALF_LIBRARY=C:/libs/OpenEXR-2.2.0-vs2015_x64_rel/lib/Half.lib -DOPENIMAGEIOHOME=C:/libs/OpenImageIO-1.8.12-vs2015_x64_rel -DLLVM_DIRECTORY=C:/libs/llvm+clang-6.0.0-win64-msvc-release -DLLVM_STATIC=1 -DCMAKE_PREFIX_PATH=C:/libs/qt5-adsk-5.6.1-vs2015_x64 -DFLEX_EXECUTABLE=C:/libs/win_flex_bison-2.5.14/win_flex.exe -DBISON_EXECUTABLE=C:/libs/win_flex_bison-2.5.14/win_bison.exe ..
msbuild "OSL.sln" /t:Build /p:Configuration=Release /p:Platform=x64
msbuild /t:Build /p:Configuration=Release INSTALL.vcxproj
```

### Versions

* OSL branch/version: master
* OS: windows 7
* C++ compiler: msvc14
* LLVM version: 6.0.0
* OIIO version:  1.8.12

**Comment by lgritz** [comment]
I believe this was fixed by #933
