### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [imageworks/OpenShadingLanguage#908]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [a function like “clear_layout”](https://github.com/imageworks/OpenShadingLanguage/blob/7f9372f7a2bcb21bbe70ceb8e61af5ca14af41af/src/osltoy/qtutils.h#L71 "Update candidate: clear_layout()").

**Comment by lgritz** [comment]
This was fixed by #920, but the issue was never closed. Closing now.
