### ISSUE TITLE
shaders are installed into non standard directory in linux build

### ISSUE THREAD

**Issue by plater** [imageworks/OpenShadingLanguage#955]
I've come across this error while packaging for openSUSE.
The shaders are installed directly under $PREFIX /usr I've attached the patch I made to ensure that the installation adheres to the linux standard base. I use -DCMAKE_INSTALL_DATADIR:PATH=%{_datadir}/%{name} other distros can put in their own paths.
[OpenShadingLanguage-shaderinstalldir.patch.txt](https://github.com/imageworks/OpenShadingLanguage/files/2720561/OpenShadingLanguage-shaderinstalldir.patch.txt)

**Comment by lgritz** [comment]
Oh, I see. Hmmm. For a system install, it does sound totally reasonable to put it in that area (which is `PREFIX/share/shaders`). But everybody is used to it going in `PREFIX/shaders`, and I'm afraid to break them. I may rework your patch into an option so people can decide. Would that work for you?

**Comment by plater** [comment]
An option is fine.
