### ISSUE TITLE
Exponentially increasing compile times in AccumAutomata

### ISSUE THREAD

**Issue by unask** [imageworks/OpenShadingLanguage#971]
Hi,

We're encountering an issue whereby certain groups of light path expression rules, when added to AccumAutomata, cause compile times to increase exponentially. The specific rules that trigger the issue are almost identical, but as each one is added, they slow compilation first by milliseconds, then seconds, then minutes. 

I profiled the code and discovered that the bottleneck is in Automata::ndfautoToDfauto(), specifically during optimisation of the DFA. It appears the graph being generated contains an unreasonably large number of states which the optimiser then struggles to efficiently reduce. 

Our shaders are using a version of OSL that's a couple of years old, so this issue might have been identified and fixed since (however, I don't anything mentioned in changes.md). Before I potentially waste someone's time with instructions to reproduce, I was wondering if anyone could comment on whether this issue has been seen before.

Regards,
Ben Spencer
DNEG

**Comment by aconty** [comment]
That code hasn't been touched in ages. It is about time someone reported an issue. It might be a limitation or maybe it is something I can fix.

Do you have like a unit test I can look at? Just hardcode the offending rules.

thanks

**Comment by unask** [comment]
Thanks for the speedy reply, @aconty! I'll put together a test for you as soon as possible.

Thanks,
Ben

**Comment by unask** [comment]
Here you go: [osl_automata_test.cpp.txt](https://github.com/imageworks/OpenShadingLanguage/files/2856800/osl_automata_test.cpp.txt)

The problem appears when you include the last 12 expressions. Remove these and compilation time drops down to a few seconds.

Thanks again for looking into this. Please let me know if I can supply any more information. 

Ben

**Comment by aconty** [comment]
From a first glance I see these trouble rules:

"C.<O.+'alphaIncand7'>"

Have a '+' modifier on the scattering symbol inside the group, which doesn't make sense to me but maybe you have a reason for it? Is the render producing more than one scattering symbol per hit?

**Comment by aconty** [comment]
The problem goes away if you omit those '+' within the groups. Have to investigate why it explodes with that, but was it intentional or accidental?

**Comment by unask** [comment]
No, you're quite correct. There's no reason for this modifier to be in the group. These regexes are usually written by render TDs who have a general idea of what they want, but arrive at a working light path expression through some amount of trial and error. 

I guess that feeds into my next question. Are these weird expressions triggering something akin to catastrophic backtracking? If this is the case then we simply need to be vigilant and properly sanitise our regexes here. That said, I can't immediately see why adding an unnecessary quantifier would cause the explosion in compilation time, so maybe it's a bug.

**Comment by aconty** [comment]
It is not a bug (as far as I can see, everything looks good). But it is a known weakness of regular expressions:

https://en.wikipedia.org/wiki/ReDoS

And it is related to catastrophic backtracing. Long story short: you either convert to DFA before parsing and are vulnerable to these tricky expressions, or you parse with backtracing and are vulnerable to malicious text. From what I gather, most implementations for text search use the backtracing approach because you need both a bad regexp and a bad input to blowup.

But we want superfast parsing, and using a DFA is the fastest possible parser. So yes, we have to be careful with the inputs. But it is a good sign that it hasn't happened for a really long time. I could add a safeguard and forbid *,+,{} inside groups, which doesn't seem useful anyway.

Does that sound good?

**Comment by pajenterprisesllc** [comment]
committee

**Comment by pajenterprisesllc** [comment]
master is here

**Comment by pajenterprisesllc** [comment]
Duplicate of #8

**Comment by lgritz** [comment]
Fixed by #972. Closing.

**Comment by unask** [comment]
> But we want superfast parsing, and using a DFA is the fastest possible parser. So yes, we have to be careful with the inputs. But it is a good sign that it hasn't happened for a really long time. I could add a safeguard and forbid *,+,{} inside groups, which doesn't seem useful anyway.
> 
> Does that sound good?

Yes, this sounds great. Between your safeguard and better awareness about ReDoS in the studio, we should be fine. 

Thanks for sorting this out!

Ben

**Comment by pajenterprisesllc** [comment]
committee
