### ISSUE TITLE
Missing implementation of ShadingSystem::Parameter(...)

### ISSUE THREAD

**Issue by cfcohen** [imageworks/OpenShadingLanguage#999]
### Problem

This commit:

https://github.com/imageworks/OpenShadingLanguage/commit/11d52bac685aca0ddb0b014780035ad7eda4e092#diff-9cb3fae78b96b16bee3dedb18f15aff1L164

appears to have incorrectly removed the implementation of:

ShadingSystem::Parameter(string_view name, TypeDesc t, const void *val)

It appears that there were some related changes involving the addition of the lockgeom boolean that caused the problem.  I suspect that the intention was for that parameter to default to true in the header, eliminating the need for the implementation, so perhaps the problem was here:

https://github.com/imageworks/OpenShadingLanguage/commit/11d52bac685aca0ddb0b014780035ad7eda4e092#diff-4f736a60bc17cab9c5d268dc522eb236R455

**Expected behavior:**  

Code that compiles should link correctly.

**Actual behavior:**  

Code fails to link because of the missing implementation.

### Steps to Reproduce

Hopefully fairly obvious.

### Versions

Current commit.

**Comment by lgritz** [comment]
Oh, I see, I think you are correct.

Sorry, that seems to have been an inadvertent loss while moving those declarations around. I will propose a fix.

**Comment by lgritz** [comment]
Proposed fix in #1000. Please give that a try if you can, see if it fixes it fully for you.
